### Create imbalanced test set

In [3]:
import pandas as pd

gencode = pd.read_csv(r'D:\Splice_FMs_seq_lengths\gencode_multi_seq_length\gencode300.csv')
gtex = pd.read_csv(r'D:\Splice_FMs_seq_lengths\gtex_multi_seq_length\gtex300.csv')

gencode[gencode['CHROM'].isin(['chr20', 'chr21'])]['Splicing_types'].value_counts()

Splicing_types
0    8962
1    8822
2    8666
Name: count, dtype: int64

In [4]:
gtex[gtex['CHROM'].isin(['chr20', 'chr21'])]['Splicing_types'].value_counts()

Splicing_types
1    13776
0    13754
2    13732
Name: count, dtype: int64

In [1]:
from pathlib import Path
import runpy

# Chay script da tao de sinh cac test set imbalanced
script_path = Path("create_imbalanced_test_sets.py")
if not script_path.exists():
    raise FileNotFoundError(f"Khong tim thay script: {script_path.resolve()}")

runpy.run_path(str(script_path), run_name="__main__")

====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gencode_multi_seq_length\gencode300.csv
Tong so mau test (chr20/chr21): 26,450
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
0    8962
1    8822
2    8666
Name: count, dtype: int64

[DONE] gencode300_test_set_1_1_10.csv
Kich thuoc: 10,752 | donor=896, acceptor=896, negative=8,960
value_counts Splicing_types (sau subsample):
Splicing_types
0    8960
1     896
2     896
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode300_test_set_1_1_20.csv
Kich thuoc: 9,856 | donor=448, acceptor=448, negative=8,960
value_counts Splicing_types (sau subsample):
Splicing_types
0    8960
2     448
1     448
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode300_test_set_1_1_50.csv
Kich thuoc: 9,308 | donor=179, acceptor=179, negative=8,950
value_counts Splicing_types (sau subsample):
Splicing_types
0    8950
1     179
2     179
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode300_test_set_1_1_100.csv
Kich thuoc: 9,078 | donor=89, acceptor=89, negative=8,900
value_counts Splicing_types (sau subsample):
Splicing_types
0    8900
2      89
1      89
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gencode_multi_seq_length\gencode600.csv
Tong so mau test (chr20/chr21): 26,401
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
0    8913
1    8822
2    8666
Name: count, dtype: int64

[DONE] gencode600_test_set_1_1_10.csv
Kich thuoc: 10,692 | donor=891, acceptor=891, negative=8,910
value_counts Splicing_types (sau subsample):
Splicing_types
0    8910
2     891
1     891
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode600_test_set_1_1_20.csv
Kich thuoc: 9,790 | donor=445, acceptor=445, negative=8,900
value_counts Splicing_types (sau subsample):
Splicing_types
0    8900
1     445
2     445
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode600_test_set_1_1_50.csv
Kich thuoc: 9,256 | donor=178, acceptor=178, negative=8,900
value_counts Splicing_types (sau subsample):
Splicing_types
0    8900
1     178
2     178
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode600_test_set_1_1_100.csv
Kich thuoc: 9,078 | donor=89, acceptor=89, negative=8,900
value_counts Splicing_types (sau subsample):
Splicing_types
0    8900
2      89
1      89
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gencode_multi_seq_length\gencode1000.csv
Tong so mau test (chr20/chr21): 26,315
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
0    8827
1    8822
2    8666
Name: count, dtype: int64

[DONE] gencode1000_test_set_1_1_10.csv
Kich thuoc: 10,584 | donor=882, acceptor=882, negative=8,820
value_counts Splicing_types (sau subsample):
Splicing_types
0    8820
1     882
2     882
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode1000_test_set_1_1_20.csv
Kich thuoc: 9,702 | donor=441, acceptor=441, negative=8,820
value_counts Splicing_types (sau subsample):
Splicing_types
0    8820
2     441
1     441
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode1000_test_set_1_1_50.csv
Kich thuoc: 9,152 | donor=176, acceptor=176, negative=8,800
value_counts Splicing_types (sau subsample):
Splicing_types
0    8800
2     176
1     176
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode1000_test_set_1_1_100.csv
Kich thuoc: 8,976 | donor=88, acceptor=88, negative=8,800
value_counts Splicing_types (sau subsample):
Splicing_types
0    8800
2      88
1      88
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gencode_multi_seq_length\gencode2000.csv
Tong so mau test (chr20/chr21): 26,364
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
0    8883
1    8818
2    8663
Name: count, dtype: int64

[DONE] gencode2000_test_set_1_1_10.csv
Kich thuoc: 10,656 | donor=888, acceptor=888, negative=8,880
value_counts Splicing_types (sau subsample):
Splicing_types
0    8880
2     888
1     888
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode2000_test_set_1_1_20.csv
Kich thuoc: 9,768 | donor=444, acceptor=444, negative=8,880
value_counts Splicing_types (sau subsample):
Splicing_types
0    8880
2     444
1     444
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode2000_test_set_1_1_50.csv
Kich thuoc: 9,204 | donor=177, acceptor=177, negative=8,850
value_counts Splicing_types (sau subsample):
Splicing_types
0    8850
1     177
2     177
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode2000_test_set_1_1_100.csv
Kich thuoc: 8,976 | donor=88, acceptor=88, negative=8,800
value_counts Splicing_types (sau subsample):
Splicing_types
0    8800
2      88
1      88
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gencode_multi_seq_length\gencode10000.csv
Tong so mau test (chr20/chr21): 26,364
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
0    8883
1    8818
2    8663
Name: count, dtype: int64

[DONE] gencode10000_test_set_1_1_10.csv
Kich thuoc: 10,656 | donor=888, acceptor=888, negative=8,880
value_counts Splicing_types (sau subsample):
Splicing_types
0    8880
2     888
1     888
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode10000_test_set_1_1_20.csv
Kich thuoc: 9,768 | donor=444, acceptor=444, negative=8,880
value_counts Splicing_types (sau subsample):
Splicing_types
0    8880
2     444
1     444
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode10000_test_set_1_1_50.csv
Kich thuoc: 9,204 | donor=177, acceptor=177, negative=8,850
value_counts Splicing_types (sau subsample):
Splicing_types
0    8850
1     177
2     177
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gencode10000_test_set_1_1_100.csv
Kich thuoc: 8,976 | donor=88, acceptor=88, negative=8,800
value_counts Splicing_types (sau subsample):
Splicing_types
0    8800
2      88
1      88
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gtex_multi_seq_length\gtex300.csv
Tong so mau test (chr20/chr21): 41,262
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
1    13776
0    13754
2    13732
Name: count, dtype: int64

[DONE] gtex300_test_set_1_1_10.csv
Kich thuoc: 16,500 | donor=1,375, acceptor=1,375, negative=13,750
value_counts Splicing_types (sau subsample):
Splicing_types
0    13750
1     1375
2     1375
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex300_test_set_1_1_20.csv
Kich thuoc: 15,114 | donor=687, acceptor=687, negative=13,740
value_counts Splicing_types (sau subsample):
Splicing_types
0    13740
2      687
1      687
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex300_test_set_1_1_50.csv
Kich thuoc: 14,300 | donor=275, acceptor=275, negative=13,750
value_counts Splicing_types (sau subsample):
Splicing_types
0    13750
2      275
1      275
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex300_test_set_1_1_100.csv
Kich thuoc: 13,974 | donor=137, acceptor=137, negative=13,700
value_counts Splicing_types (sau subsample):
Splicing_types
0    13700
2      137
1      137
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gtex_multi_seq_length\gtex600.csv
Tong so mau test (chr20/chr21): 41,261
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
1    13776
0    13754
2    13731
Name: count, dtype: int64

[DONE] gtex600_test_set_1_1_10.csv
Kich thuoc: 16,500 | donor=1,375, acceptor=1,375, negative=13,750
value_counts Splicing_types (sau subsample):
Splicing_types
0    13750
1     1375
2     1375
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex600_test_set_1_1_20.csv
Kich thuoc: 15,114 | donor=687, acceptor=687, negative=13,740
value_counts Splicing_types (sau subsample):
Splicing_types
0    13740
2      687
1      687
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex600_test_set_1_1_50.csv
Kich thuoc: 14,300 | donor=275, acceptor=275, negative=13,750
value_counts Splicing_types (sau subsample):
Splicing_types
0    13750
2      275
1      275
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex600_test_set_1_1_100.csv
Kich thuoc: 13,974 | donor=137, acceptor=137, negative=13,700
value_counts Splicing_types (sau subsample):
Splicing_types
0    13700
2      137
1      137
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gtex_multi_seq_length\gtex1000.csv
Tong so mau test (chr20/chr21): 41,258
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
1    13775
0    13753
2    13730
Name: count, dtype: int64

[DONE] gtex1000_test_set_1_1_10.csv
Kich thuoc: 16,500 | donor=1,375, acceptor=1,375, negative=13,750
value_counts Splicing_types (sau subsample):
Splicing_types
0    13750
1     1375
2     1375
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex1000_test_set_1_1_20.csv
Kich thuoc: 15,114 | donor=687, acceptor=687, negative=13,740
value_counts Splicing_types (sau subsample):
Splicing_types
0    13740
2      687
1      687
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex1000_test_set_1_1_50.csv
Kich thuoc: 14,300 | donor=275, acceptor=275, negative=13,750
value_counts Splicing_types (sau subsample):
Splicing_types
0    13750
2      275
1      275
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex1000_test_set_1_1_100.csv
Kich thuoc: 13,974 | donor=137, acceptor=137, negative=13,700
value_counts Splicing_types (sau subsample):
Splicing_types
0    13700
2      137
1      137
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gtex_multi_seq_length\gtex2000.csv
Tong so mau test (chr20/chr21): 41,064
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
1    13712
0    13688
2    13664
Name: count, dtype: int64

[DONE] gtex2000_test_set_1_1_10.csv
Kich thuoc: 16,416 | donor=1,368, acceptor=1,368, negative=13,680
value_counts Splicing_types (sau subsample):
Splicing_types
0    13680
2     1368
1     1368
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex2000_test_set_1_1_20.csv
Kich thuoc: 15,048 | donor=684, acceptor=684, negative=13,680
value_counts Splicing_types (sau subsample):
Splicing_types
0    13680
1      684
2      684
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex2000_test_set_1_1_50.csv
Kich thuoc: 14,196 | donor=273, acceptor=273, negative=13,650
value_counts Splicing_types (sau subsample):
Splicing_types
0    13650
2      273
1      273
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex2000_test_set_1_1_100.csv
Kich thuoc: 13,872 | donor=136, acceptor=136, negative=13,600
value_counts Splicing_types (sau subsample):
Splicing_types
0    13600
2      136
1      136
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
====================================================================================================
Dang xu ly: D:\Splice_FMs_seq_lengths\gtex_multi_seq_length\gtex10000.csv
Tong so mau test (chr20/chr21): 41,064
value_counts Splicing_types (tap test truoc subsample):
Splicing_types
1    13712
0    13688
2    13664
Name: count, dtype: int64

[DONE] gtex10000_test_set_1_1_10.csv
Kich thuoc: 16,416 | donor=1,368, acceptor=1,368, negative=13,680
value_counts Splicing_types (sau subsample):
Splicing_types
0    13680
2     1368
1     1368
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex10000_test_set_1_1_20.csv
Kich thuoc: 15,048 | donor=684, acceptor=684, negative=13,680
value_counts Splicing_types (sau subsample):
Splicing_types
0    13680
1      684
2      684
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex10000_test_set_1_1_50.csv
Kich thuoc: 14,196 | donor=273, acceptor=273, negative=13,650
value_counts Splicing_types (sau subsample):
Splicing_types
0    13650
2      273
1      273
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
[DONE] gtex10000_test_set_1_1_100.csv
Kich thuoc: 13,872 | donor=136, acceptor=136, negative=13,600
value_counts Splicing_types (sau subsample):
Splicing_types
0    13600
2      136
1      136
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
Hoan tat tao cac tap test imbalanced.

{'__name__': '__main__',
 '__doc__': None,
 '__package__': '',
 '__loader__': None,
 '__spec__': None,
 '__file__': 'create_imbalanced_test_sets.py',
 '__cached__': None,
 '__builtins__': {'__name__': 'builtins',
  '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.",
  '__package__': '',
  '__loader__': _frozen_importlib.BuiltinImporter,
  '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
  '__build_class__': <function __build_class__>,
  '__import__': <function __import__>,
  'abs': <function abs(x, /)>,
  'all': <function all(iterable, /)>,
  'any': <function any(iterable, /)>,
  'ascii': <function ascii(obj, /)>,
  'bin': <function bin(number, /)>,
  'breakpoint': <function breakpoint>,
  'callable': <function callable(obj, /)>,
  'chr': <function chr(i, /)>,
  'compile': <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>,
  'delattr': <function delattr(obj, name, /)>,
  'dir': <function dir>,
  'divmod': <function divmod(x, y, /)>,
  'eval': <function eval(source, globals=None, locals=None, /)>,
  'exec': <function exec(source, globals=None, locals=None, /)>,
  'format': <function format(value, format_spec='', /)>,
  'getattr': <function getattr>,
  'globals': <function globals()>,
  'hasattr': <function hasattr(obj, name, /)>,
  'hash': <function hash(obj, /)>,
  'hex': <function hex(number, /)>,
  'id': <function id(obj, /)>,
  'input': <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x0000021815DADBA0>>,
  'isinstance': <function isinstance(obj, class_or_tuple, /)>,
  'issubclass': <function issubclass(cls, class_or_tuple, /)>,
  'iter': <function iter>,
  'aiter': <function aiter(async_iterable, /)>,
  'len': <function len(obj, /)>,
  'locals': <function locals()>,
  'max': <function max>,
  'min': <function min>,
  'next': <function next>,
  'anext': <function anext>,
  'oct': <function oct(number, /)>,
  'ord': <function ord(c, /)>,
  'pow': <function pow(base, exp, mod=None)>,
  'print': <function print>,
  'repr': <function repr(obj, /)>,
  'round': <function round(number, ndigits=None)>,
  'setattr': <function setattr(obj, name, value, /)>,
  'sorted': <function sorted(iterable, /, *, key=None, reverse=False)>,
  'sum': <function sum(iterable, /, start=0)>,
  'vars': <function vars>,
  'None': None,
  'Ellipsis': Ellipsis,
  'NotImplemented': NotImplemented,
  'False': False,
  'True': True,
  'bool': bool,
  'memoryview': memoryview,
  'bytearray': bytearray,
  'bytes': bytes,
  'classmethod': classmethod,
  'complex': complex,
  'dict': dict,
  'enumerate': enumerate,
  'filter': filter,
  'float': float,
  'frozenset': frozenset,
  'property': property,
  'int': int,
  'list': list,
  'map': map,
  'object': object,
  'range': range,
  'reversed': reversed,
  'set': set,
  'slice': slice,
  'staticmethod': staticmethod,
  'str': str,
  'super': super,
  'tuple': tuple,
  'type': type,
  'zip': zip,
  '__debug__': True,
  'BaseException': BaseException,
  'Exception': Exception,
  'TypeError': TypeError,
  'StopAsyncIteration': StopAsyncIteration,
  'StopIteration': StopIteration,
  'GeneratorExit': GeneratorExit,
  'SystemExit': SystemExit,
  'KeyboardInterrupt': KeyboardInterrupt,
  'ImportError': ImportError,
  'ModuleNotFoundError': ModuleNotFoundError,
  'OSError': OSError,
  'EnvironmentError': OSError,
  'IOError': OSError,
  'WindowsError': OSError,
  'EOFError': EOFError,
  'RuntimeError': RuntimeError,
  'RecursionError': RecursionError,
  'NotImplementedError': NotImplementedError,
  'NameError': NameError,
  'UnboundLocalError': UnboundLocalError,
  'AttributeError': AttributeError,
  'SyntaxError': SyntaxError,
  'IndentationError': IndentationError,
  'TabError': TabError,
  'LookupError': LookupError,
  'IndexError': IndexError,
  'KeyError': KeyError,
  'ValueError': ValueError,
  'UnicodeError': UnicodeError,
  'UnicodeEncodeError': UnicodeEncodeError,
  'UnicodeDecodeError': UnicodeDecodeError,
  'UnicodeTranslateError': UnicodeTranslateError,
  'AssertionError': AssertionError,
  'ArithmeticError': ArithmeticError,
  'FloatingPointError': FloatingPointError,
  'OverflowError': OverflowError,
  'ZeroDivisionError': ZeroDivisionError,
  'SystemError': SystemError,
  'ReferenceError': ReferenceError,
  'MemoryError': MemoryError,
  'BufferError': BufferError,
  'Warning': Warning,
  'UserWarning': UserWarning,
  'EncodingWarning': EncodingWarning,
  'DeprecationWarning': DeprecationWarning,
  'PendingDeprecationWarning': PendingDeprecationWarning,
  'SyntaxWarning': SyntaxWarning,
  'RuntimeWarning': RuntimeWarning,
  'FutureWarning': FutureWarning,
  'ImportWarning': ImportWarning,
  'UnicodeWarning': UnicodeWarning,
  'BytesWarning': BytesWarning,
  'ResourceWarning': ResourceWarning,
  'ConnectionError': ConnectionError,
  'BlockingIOError': BlockingIOError,
  'BrokenPipeError': BrokenPipeError,
  'ChildProcessError': ChildProcessError,
  'ConnectionAbortedError': ConnectionAbortedError,
  'ConnectionRefusedError': ConnectionRefusedError,
  'ConnectionResetError': ConnectionResetError,
  'FileExistsError': FileExistsError,
  'FileNotFoundError': FileNotFoundError,
  'IsADirectoryError': IsADirectoryError,
  'NotADirectoryError': NotADirectoryError,
  'InterruptedError': InterruptedError,
  'PermissionError': PermissionError,
  'ProcessLookupError': ProcessLookupError,
  'TimeoutError': TimeoutError,
  'open': <function io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
  'copyright': Copyright (c) 2001-2023 Python Software Foundation.
  All Rights Reserved.

  Copyright (c) 2000 BeOpen.com.
  All Rights Reserved.

  Copyright (c) 1995-2001 Corporation for National Research Initiatives.
  All Rights Reserved.

  Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
  All Rights Reserved.,
  'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
      for supporting Python development.  See www.python.org for more information.,
  'license': See https://www.python.org/psf/license/,
  'help': Type help() for interactive help, or help(object) for help about object.,
  'execfile': <function _pydev_bundle._pydev_execfile.execfile(file, glob=None, loc=None)>,
  'runfile': <function _pydev_bundle.pydev_umd.runfile(filename, args=None, wdir=None, namespace=None)>,
  '__IPYTHON__': True,
  'display': <function IPython.core.display_functions.display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)>,
  'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x0000021816229540>>},
 'annotations': _Feature((3, 7, 0, 'beta', 1), (3, 11, 0, 'alpha', 0), 16777216),
 'Path': pathlib.Path,
 'Dict': typing.Dict,
 'Iterable': typing.Iterable,
 'Tuple': typing.Tuple,
 'pd': <module 'pandas' from 'c:\\Users\\Dung\\anaconda3\\envs\\splice_env\\lib\\site-packages\\pandas\\__init__.py'>,
 'SEED': 42,
 'WINDOWS': [300, 600, 1000, 2000, 10000],
 'RATIOS': [10, 20, 50, 100],
 'CHROMS': {'chr20', 'chr21'},
 'detect_label_mapping': <function __main__.detect_label_mapping(values: 'Iterable[object]') -> 'Dict[str, object]'>,
 'sample_ratio_dataframe': <function __main__.sample_ratio_dataframe(df: 'pd.DataFrame', ratio: 'int', seed: 'int') -> 'Tuple[pd.DataFrame, Dict[str, int]]'>,
 'process_dataset': <function __main__.process_dataset(source_name: 'str', source_dir: 'Path', output_dir: 'Path', windows: 'Iterable[int]', ratios: 'Iterable[int]', seed: 'int') -> 'None'>,
 'main': <function __main__.main() -> 'None'>}

In [2]:
from pathlib import Path

base_dir = Path.cwd()
out_gencode = base_dir / "gencode"
out_gtex = base_dir / "gtex"

print("GENCODE outputs:")
if out_gencode.exists():
    for p in sorted(out_gencode.glob("*.csv")):
        print(" -", p.name)
else:
    print(" - Chua co thu muc gencode")

print("\nGTEx outputs:")
if out_gtex.exists():
    for p in sorted(out_gtex.glob("*.csv")):
        print(" -", p.name)
else:
    print(" - Chua co thu muc gtex")

GENCODE outputs:
 - gencode10000_test_set_1_1_10.csv
 - gencode10000_test_set_1_1_100.csv
 - gencode10000_test_set_1_1_20.csv
 - gencode10000_test_set_1_1_50.csv
 - gencode1000_test_set_1_1_10.csv
 - gencode1000_test_set_1_1_100.csv
 - gencode1000_test_set_1_1_20.csv
 - gencode1000_test_set_1_1_50.csv
 - gencode2000_test_set_1_1_10.csv
 - gencode2000_test_set_1_1_100.csv
 - gencode2000_test_set_1_1_20.csv
 - gencode2000_test_set_1_1_50.csv
 - gencode300_test_set_1_1_10.csv
 - gencode300_test_set_1_1_100.csv
 - gencode300_test_set_1_1_20.csv
 - gencode300_test_set_1_1_50.csv
 - gencode600_test_set_1_1_10.csv
 - gencode600_test_set_1_1_100.csv
 - gencode600_test_set_1_1_20.csv
 - gencode600_test_set_1_1_50.csv

GTEx outputs:
 - gtex10000_test_set_1_1_10.csv
 - gtex10000_test_set_1_1_100.csv
 - gtex10000_test_set_1_1_20.csv
 - gtex10000_test_set_1_1_50.csv
 - gtex1000_test_set_1_1_10.csv
 - gtex1000_test_set_1_1_100.csv
 - gtex1000_test_set_1_1_20.csv
 - gtex1000_test_set_1_1_50.csv
 - gtex2000_test_set_1_1_10.csv
 - gtex2000_test_set_1_1_100.csv
 - gtex2000_test_set_1_1_20.csv
 - gtex2000_test_set_1_1_50.csv
 - gtex300_test_set_1_1_10.csv
 - gtex300_test_set_1_1_100.csv
 - gtex300_test_set_1_1_20.csv
 - gtex300_test_set_1_1_50.csv
 - gtex600_test_set_1_1_10.csv
 - gtex600_test_set_1_1_100.csv
 - gtex600_test_set_1_1_20.csv
 - gtex600_test_set_1_1_50.csv

### Extract embedding

In [1]:
import os
import sys
import importlib
from pathlib import Path

import pandas as pd
import torch

# Khong dung flash/triton kernels de giam loi runtime
os.environ['FLASH_ATTENTION_DISABLE'] = '1'
os.environ['USE_FLASH_ATTENTION'] = '0'
os.environ['TRITON_DISABLE_LINE_INFO'] = '1'

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root / 'src'))

import config
import models
import splicing_embed_extract
importlib.reload(config)
importlib.reload(models)
importlib.reload(splicing_embed_extract)

from config import EMBEDDINGS_DIR, EMBEDDING_CONFIG, MODELS_CONFIG
from splicing_embed_extract import EmbeddingExtractor

device = 'cuda' if torch.cuda.is_available() else 'cpu'
extractor = EmbeddingExtractor(device=device)

print(f'Project root: {project_root}')
print(f'Device: {device}')
print(f'Embeddings dir: {EMBEDDINGS_DIR}')
print(f'Model families: {list(MODELS_CONFIG.keys())}')

2026-04-12 15:55:31,198 - splicing_embed_extract - INFO - Configured safe attention backend: flash_sdp=False, mem_efficient_sdp=False, math_sdp=True

Project root: d:\Splice_FMs_seq_lengths
Device: cuda
Embeddings dir: d:\Splice_FMs_seq_lengths\data\embeddings
Model families: ['HyenaDNA', 'DNABert', 'NucleotideTransformer']

In [ ]:
from typing import Dict, List
import gc
import json
import time
import inspect
from datetime import datetime

import numpy as np

try:
    import psutil
except Exception:
    psutil = None

WINDOWS = [300, 600, 1000, 2000, 10000]
IMBALANCED_RATIOS = ['1_1_10', '1_1_20', '1_1_50', '1_1_100']
RAW_RATIO_TAG = '1_1_raw'

IMBALANCED_SOURCE_DIRS = {
    'gencode': Path.cwd() / 'gencode',
    'gtex': Path.cwd() / 'gtex',
}

RAW_DEFAULT_DIR = Path.cwd() / 'raw_default_test_set'
RAW_DEFAULT_DIR.mkdir(parents=True, exist_ok=True)

TELEMETRY_DIR = project_root / 'results' / 'pipeline_telemetry'
TELEMETRY_DIR.mkdir(parents=True, exist_ok=True)
extract_timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

def _effective_settings(model_name, tokenizer, window_size: int):
    max_length = EMBEDDING_CONFIG.get('max_length', window_size)
    if model_name == 'DNABert':
        tok_max = getattr(tokenizer, 'model_max_length', None)
        if isinstance(tok_max, int) and 0 < tok_max < 100000:
            max_length = min(max_length, tok_max)
        else:
            max_length = min(max_length, 512)
        method = 'center'
        use_fp16 = False
    else:
        method = 'center'
        use_fp16 = EMBEDDING_CONFIG.get('use_fp16', False)
    batch_size = EMBEDDING_CONFIG.get('batch_size_by_window', {}).get(
        window_size, EMBEDDING_CONFIG.get('batch_size', 64)
    )
    return max_length, batch_size, method, use_fp16

def _param_stats(model: torch.nn.Module):
    param_count = sum(p.numel() for p in model.parameters())
    param_mem_bytes = sum(p.numel() * p.element_size() for p in model.parameters())
    return int(param_count), float(param_mem_bytes / (1024 ** 2))

def _measure_fm_gflops_per_sample(model, tokenizer, sample_seq: str, max_length: int):
    enc = tokenizer(
        [sample_seq],
        return_tensors='pt',
        padding=True,
        truncation=True,
        max_length=max_length,
        return_attention_mask=True,
    )
    input_ids = enc['input_ids'].to(device)
    attention_mask = enc['attention_mask'].to(device)

    try:
        model_forward_params = set(inspect.signature(model.forward).parameters.keys())
    except Exception:
        model_forward_params = {'input_ids', 'attention_mask'}

    model_inputs = {'input_ids': input_ids}
    if 'attention_mask' in model_forward_params:
        model_inputs['attention_mask'] = attention_mask

    # 1) Prefer torch profiler FLOPs (full-graph when supported)
    try:
        activities = [torch.profiler.ProfilerActivity.CPU]
        if device == 'cuda' and torch.cuda.is_available():
            activities.append(torch.profiler.ProfilerActivity.CUDA)

        with torch.inference_mode():
            with torch.profiler.profile(
                activities=activities,
                with_flops=True,
                record_shapes=True,
                acc_events=True,
            ) as prof:
                _ = model(**model_inputs)

        total_flops = 0.0
        for evt in prof.key_averages():
            evt_flops = getattr(evt, 'flops', 0)
            if evt_flops is not None:
                total_flops += float(evt_flops)

        if total_flops > 0:
            return total_flops / 1e9, 'measured_profiler'
    except Exception:
        pass

    # 2) Fallback: measured FLOPs from executed nn.Linear layers via hooks
    linear_flops = {'value': 0.0}
    handles = []

    def _linear_hook(module, module_inputs, module_output):
        try:
            in_features = int(module.in_features)
            out_features = int(module.out_features)

            if isinstance(module_output, tuple):
                out_tensor = module_output[0]
            else:
                out_tensor = module_output

            if not torch.is_tensor(out_tensor):
                return

            vectors = out_tensor.numel() / max(1, out_features)
            linear_flops['value'] += vectors * ((2.0 * in_features * out_features) + out_features)
        except Exception:
            return

    for mod in model.modules():
        if isinstance(mod, torch.nn.Linear):
            handles.append(mod.register_forward_hook(_linear_hook))

    try:
        with torch.inference_mode():
            _ = model(**model_inputs)
    finally:
        for h in handles:
            h.remove()

    if linear_flops['value'] > 0:
        return linear_flops['value'] / 1e9, 'measured_linear_hooks'

    raise RuntimeError('Khong do duoc FM GFLOPs (profiler + linear hooks deu that bai).')

def _build_raw_default_csv(window_size: int, source_name: str):
    if source_name == 'gencode':
        source_file = project_root / 'gencode_multi_seq_length' / f'gencode{window_size}.csv'
    else:
        source_file = project_root / 'gtex_multi_seq_length' / f'gtex{window_size}.csv'

    if not source_file.exists():
        raise FileNotFoundError(f'Khong tim thay file goc: {source_file}')

    df = pd.read_csv(source_file)
    if 'CHROM' not in df.columns:
        raise ValueError(f'File {source_file} thieu cot CHROM')

    raw_test_df = df[df['CHROM'].isin(['chr20', 'chr21'])].copy()
    out_file = RAW_DEFAULT_DIR / f'{source_name}{window_size}_test_set_{RAW_RATIO_TAG}.csv'
    raw_test_df.to_csv(out_file, index=False)
    return out_file

def _extract_for_csv(
    extractor_obj,
    model,
    tokenizer,
    csv_path: Path,
    output_path: Path,
    model_name: str,
    model_id: str,
    window_size: int,
    source_name: str,
    ratio: str,
    fm_param_count: int,
    fm_param_memory_mb: float,
    fm_gflops_per_sample: float,
    fm_gflops_method: str,
    telemetry_rows: list,
    force_reextract: bool = True,
):
    df = pd.read_csv(csv_path)
    if 'sequence' not in df.columns or 'Splicing_types' not in df.columns:
        raise ValueError(f'File {csv_path} thieu cot sequence hoac Splicing_types')

    if force_reextract and output_path.exists():
        output_path.unlink()

    sequences = df['sequence'].values
    labels = df['Splicing_types'].values
    max_length, batch_size, method, use_fp16 = _effective_settings(model_name, tokenizer, window_size)

    cpu_before_mb = np.nan
    cpu_after_mb = np.nan
    if psutil is not None:
        proc = psutil.Process()
        cpu_before_mb = proc.memory_info().rss / (1024 ** 2)

    if device == 'cuda' and torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    start_time = time.perf_counter()
    ok = extractor_obj._extract_with_fallback(
        sequences=sequences,
        labels=labels,
        model=model,
        tokenizer=tokenizer,
        output_file=output_path,
        max_length=max_length,
        batch_size=batch_size,
        method=method,
        use_fp16_current=use_fp16,
    )
    elapsed = float(time.perf_counter() - start_time)

    if not ok:
        raise RuntimeError(f'Extract failed for {csv_path.name}')

    gpu_peak_mb = np.nan
    if device == 'cuda' and torch.cuda.is_available():
        gpu_peak_mb = float(torch.cuda.max_memory_allocated() / (1024 ** 2))

    if psutil is not None:
        proc = psutil.Process()
        cpu_after_mb = proc.memory_info().rss / (1024 ** 2)

    telemetry_rows.append({
        'timestamp': extract_timestamp,
        'stage': 'extract_embedding',
        'family': model_name,
        'model_id': model_id,
        'model_variant': model_id,
        'window_size': int(window_size),
        'dataset': source_name,
        'ratio': ratio,
        'input_csv': str(csv_path),
        'output_embedding': str(output_path),
        'n_samples': int(len(df)),
        'running_time_seconds': elapsed,
        'param_count': int(fm_param_count),
        'model_param_memory_mb': float(fm_param_memory_mb),
        'gpu_peak_memory_mb': float(gpu_peak_mb),
        'cpu_ram_delta_mb': float(cpu_after_mb - cpu_before_mb) if psutil is not None else np.nan,
        'gflops_per_sample': float(fm_gflops_per_sample),
        'gflops_total': float(fm_gflops_per_sample * len(df)),
        'gflops_method': fm_gflops_method,
        'batch_size': int(batch_size),
        'max_length': int(max_length),
        'pooling_method': method,
    })

extract_telemetry_rows = []

for window_size in WINDOWS:
    print('\n' + '=' * 100)
    print(f'WINDOW {window_size}')

    raw_csv_by_source = {}
    for source_name in ['gencode', 'gtex']:
        raw_csv = _build_raw_default_csv(window_size, source_name)
        raw_csv_by_source[source_name] = raw_csv
        print(f'[RAW ] {raw_csv.name}')

    for model_name, model_cfg in MODELS_CONFIG.items():
        for model_id in model_cfg.get('model_ids', []):
            skip_reason = config.get_model_window_skip_reason(model_name, model_id, window_size)
            if skip_reason is not None:
                print(f'[SKIP] {skip_reason}')
                continue

            combo_name = f'{model_name}_{model_id}'
            model_dir = EMBEDDINGS_DIR / str(window_size) / combo_name
            model_dir.mkdir(parents=True, exist_ok=True)

            print('\n' + '-' * 100)
            print(f'Loading model: {combo_name}')
            model, tokenizer = extractor.model_loader.load_model_by_name(model_name, model_id)

            fm_param_count, fm_param_memory_mb = _param_stats(model)
            probe_seq = 'ACGT' * max(50, min(window_size // 4, 500))
            fm_gflops_per_sample, fm_gflops_method = _measure_fm_gflops_per_sample(
                model=model,
                tokenizer=tokenizer,
                sample_seq=probe_seq,
                max_length=window_size,
            )
            print(
                f'[FM] params={fm_param_count:,} | param_mem_mb={fm_param_memory_mb:.2f} | '
                f'gflops_per_sample={fm_gflops_per_sample:.4f} ({fm_gflops_method})'
            )

            for source_name in ['gencode', 'gtex']:
                raw_csv = raw_csv_by_source[source_name]
                if source_name == 'gencode':
                    raw_out = model_dir / 'test_embeddings.pt'
                else:
                    raw_out = model_dir / 'gtex_test_embeddings.pt'
                print(f'[RUN ] {raw_csv.name} -> {raw_out.name}')
                _extract_for_csv(
                    extractor_obj=extractor,
                    model=model,
                    tokenizer=tokenizer,
                    csv_path=raw_csv,
                    output_path=raw_out,
                    model_name=model_name,
                    model_id=model_id,
                    window_size=window_size,
                    source_name=source_name,
                    ratio=RAW_RATIO_TAG,
                    fm_param_count=fm_param_count,
                    fm_param_memory_mb=fm_param_memory_mb,
                    fm_gflops_per_sample=fm_gflops_per_sample,
                    fm_gflops_method=fm_gflops_method,
                    telemetry_rows=extract_telemetry_rows,
                    force_reextract=True,
                )

            for source_name, source_dir in IMBALANCED_SOURCE_DIRS.items():
                for ratio in IMBALANCED_RATIOS:
                    csv_file = source_dir / f'{source_name}{window_size}_test_set_{ratio}.csv'
                    if not csv_file.exists():
                        print(f'[SKIP] Missing: {csv_file}')
                        continue

                    if source_name == 'gencode':
                        out_file = model_dir / f'test_{ratio}_embeddings.pt'
                    else:
                        out_file = model_dir / f'gtex_test_{ratio}_embeddings.pt'

                    print(f'[RUN ] {csv_file.name} -> {out_file.name}')
                    _extract_for_csv(
                        extractor_obj=extractor,
                        model=model,
                        tokenizer=tokenizer,
                        csv_path=csv_file,
                        output_path=out_file,
                        model_name=model_name,
                        model_id=model_id,
                        window_size=window_size,
                        source_name=source_name,
                        ratio=ratio,
                        fm_param_count=fm_param_count,
                        fm_param_memory_mb=fm_param_memory_mb,
                        fm_gflops_per_sample=fm_gflops_per_sample,
                        fm_gflops_method=fm_gflops_method,
                        telemetry_rows=extract_telemetry_rows,
                        force_reextract=True,
                    )

            del model
            del tokenizer
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

if not extract_telemetry_rows:
    raise RuntimeError('Khong tao duoc telemetry extract nao. Kiem tra input CSV.')

extract_df = pd.DataFrame(extract_telemetry_rows)
extract_long_csv = TELEMETRY_DIR / f'extract_telemetry_long_{extract_timestamp}.csv'
extract_long_json = TELEMETRY_DIR / f'extract_telemetry_long_{extract_timestamp}.json'
extract_df.to_csv(extract_long_csv, index=False)
extract_df.to_json(extract_long_json, orient='records', indent=2)

extract_window_df = (
    extract_df.groupby(['family', 'model_id', 'model_variant', 'window_size'], as_index=False)
    .agg({
        'running_time_seconds': 'sum',
        'n_samples': 'sum',
        'param_count': 'first',
        'model_param_memory_mb': 'first',
        'gpu_peak_memory_mb': 'max',
        'cpu_ram_delta_mb': 'sum',
        'gflops_per_sample': 'first',
        'gflops_total': 'sum',
        'gflops_method': 'first',
    })
    .rename(columns={
        'running_time_seconds': 'fm_running_time_seconds',
        'param_count': 'fm_param_count',
        'model_param_memory_mb': 'fm_model_param_memory_mb',
        'gpu_peak_memory_mb': 'fm_gpu_peak_memory_mb',
        'cpu_ram_delta_mb': 'fm_cpu_ram_delta_mb',
        'gflops_per_sample': 'fm_gflops_per_sample',
        'gflops_total': 'fm_gflops_total',
    })
)

extract_window_csv = TELEMETRY_DIR / f'extract_telemetry_model_window_{extract_timestamp}.csv'
extract_window_json = TELEMETRY_DIR / f'extract_telemetry_model_window_{extract_timestamp}.json'
extract_window_df.to_csv(extract_window_csv, index=False)
extract_window_df.to_json(extract_window_json, orient='records', indent=2)

print('\nDone extracting embeddings (raw + imbalanced) for all MODELS_CONFIG models.')
print(f'[SAVED] {extract_long_csv.name} | rows={len(extract_df)}')
print(f'[SAVED] {extract_long_json.name} | rows={len(extract_df)}')
print(f'[SAVED] {extract_window_csv.name} | rows={len(extract_window_df)}')
print(f'[SAVED] {extract_window_json.name} | rows={len(extract_window_df)}')

====================================================================================================
WINDOW 300
[RAW ] gencode300_test_set_1_1_raw.csv
[RAW ] gtex300_test_set_1_1_raw.csv

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf

2026-04-12 02:25:39,478 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:39,516 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/config.json "HTTP/1.1 200 OK"
2026-04-12 02:25:39,786 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/configuration_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:39,828 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/configuration_hyena.py "HTTP/1.1 200 OK"
2026-04-12 02:25:40,097 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:40,132 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/config.json "HTTP/1.1 200 OK"
2026-04-12 02:25:40,403 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:40,432 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 02:25:40,696 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/tokenization_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:40,726 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/tokenization_hyena.py "HTTP/1.1 200 OK"
2026-04-12 02:25:40,993 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/LongSafari/hyenadna-small-32k-seqlen-hf/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 02:25:41,275 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/LongSafari/hyenadna-small-32k-seqlen-hf/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 02:25:41,540 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:41,570 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/config.json "HTTP/1.1 200 OK"
2026-04-12 02:25:41,828 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/configuration_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:41,863 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/configuration_hyena.py "HTTP/1.1 200 OK"
2026-04-12 02:25:42,128 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-12 02:25:42,128 - huggingface_hub.utils._http - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-12 02:25:42,162 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/config.json "HTTP/1.1 200 OK"
2026-04-12 02:25:42,428 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-small-32k-seqlen-hf/resolve/main/modeling_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:25:42,466 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-small-32k-seqlen-hf/8fe770c78eb13fe33bf81501612faeddf4d6f331/modeling_hyena.py "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

HyenaDNAModel LOAD REPORT from: LongSafari/hyenadna-small-32k-seqlen-hf
Key            | Status     |  |
---------------+------------+--+-
lm_head.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-04-12 02:25:42,652 - models - INFO - Successfully loaded HyenaDNA model: LongSafari/hyenadna-small-32k-seqlen-hf
2026-04-12 02:25:42,960 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26450 sequences
2026-04-12 02:25:42,960 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[FM] params=3,277,568 | param_mem_mb=12.50 | gflops_per_sample=1.9500 (measured_profiler)
[RUN ] gencode300_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 104/104 [00:20<00:00,  5.20it/s]
2026-04-12 02:26:02,990 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_embeddings.pt
2026-04-12 02:26:02,992 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 256]), labels=torch.Size([26450])
2026-04-12 02:26:03,095 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41262 sequences
2026-04-12 02:26:03,095 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 162/162 [00:30<00:00,  5.30it/s]
2026-04-12 02:26:33,683 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 02:26:33,684 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 256]), labels=torch.Size([41262])
2026-04-12 02:26:33,723 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10752 sequences
2026-04-12 02:26:33,724 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 42/42 [00:07<00:00,  5.26it/s]
2026-04-12 02:26:41,711 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 02:26:41,711 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 256]), labels=torch.Size([10752])
2026-04-12 02:26:41,745 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9856 sequences
2026-04-12 02:26:41,745 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 39/39 [00:07<00:00,  5.14it/s]
2026-04-12 02:26:49,350 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 02:26:49,350 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 256]), labels=torch.Size([9856])
2026-04-12 02:26:49,380 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9308 sequences
2026-04-12 02:26:49,380 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 37/37 [00:07<00:00,  5.21it/s]
2026-04-12 02:26:56,487 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 02:26:56,488 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 256]), labels=torch.Size([9308])
2026-04-12 02:26:56,526 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:26:56,527 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 36/36 [00:06<00:00,  5.17it/s]
2026-04-12 02:27:03,498 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 02:27:03,498 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 256]), labels=torch.Size([9078])
2026-04-12 02:27:03,544 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:27:03,544 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 65/65 [00:12<00:00,  5.04it/s]
2026-04-12 02:27:16,463 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:27:16,463 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 256]), labels=torch.Size([16500])
2026-04-12 02:27:16,507 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:27:16,508 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 60/60 [00:11<00:00,  5.02it/s]
2026-04-12 02:27:28,478 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:27:28,478 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 256]), labels=torch.Size([15114])
2026-04-12 02:27:28,527 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:27:28,527 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 56/56 [00:10<00:00,  5.14it/s]
2026-04-12 02:27:39,426 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:27:39,426 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 256]), labels=torch.Size([14300])
2026-04-12 02:27:39,471 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:27:39,471 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 55/55 [00:10<00:00,  5.28it/s]
2026-04-12 02:27:49,887 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:27:49,887 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 256]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf

2026-04-12 02:27:50,346 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:50,375 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/config.json "HTTP/1.1 200 OK"
2026-04-12 02:27:50,641 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/configuration_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:50,669 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/configuration_hyena.py "HTTP/1.1 200 OK"
2026-04-12 02:27:50,943 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:50,970 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/config.json "HTTP/1.1 200 OK"
2026-04-12 02:27:51,244 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:51,270 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 02:27:51,544 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/tokenization_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:51,572 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/tokenization_hyena.py "HTTP/1.1 200 OK"
2026-04-12 02:27:51,862 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/LongSafari/hyenadna-medium-160k-seqlen-hf/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 02:27:52,126 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/LongSafari/hyenadna-medium-160k-seqlen-hf/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 02:27:52,403 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:52,433 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/config.json "HTTP/1.1 200 OK"
2026-04-12 02:27:52,698 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/configuration_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:52,726 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/configuration_hyena.py "HTTP/1.1 200 OK"
2026-04-12 02:27:53,001 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:53,029 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/config.json "HTTP/1.1 200 OK"
2026-04-12 02:27:53,306 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/LongSafari/hyenadna-medium-160k-seqlen-hf/resolve/main/modeling_hyena.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:27:53,334 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/LongSafari/hyenadna-medium-160k-seqlen-hf/7ebf71773d22c0ede2cc55cb2be15ee8c289e1ce/modeling_hyena.py "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HyenaDNAModel LOAD REPORT from: LongSafari/hyenadna-medium-160k-seqlen-hf
Key            | Status     |  |
---------------+------------+--+-
lm_head.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-04-12 02:27:53,556 - models - INFO - Successfully loaded HyenaDNA model: LongSafari/hyenadna-medium-160k-seqlen-hf
2026-04-12 02:27:53,768 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26450 sequences
2026-04-12 02:27:53,769 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[FM] params=6,550,528 | param_mem_mb=24.99 | gflops_per_sample=3.8999 (measured_profiler)
[RUN ] gencode300_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 104/104 [00:22<00:00,  4.57it/s]
2026-04-12 02:28:16,546 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_embeddings.pt
2026-04-12 02:28:16,546 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 256]), labels=torch.Size([26450])
2026-04-12 02:28:16,643 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41262 sequences
2026-04-12 02:28:16,643 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 162/162 [00:35<00:00,  4.57it/s]
2026-04-12 02:28:52,114 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 02:28:52,114 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 256]), labels=torch.Size([41262])
2026-04-12 02:28:52,153 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10752 sequences
2026-04-12 02:28:52,153 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 42/42 [00:09<00:00,  4.48it/s]
2026-04-12 02:29:01,529 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 02:29:01,529 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 256]), labels=torch.Size([10752])
2026-04-12 02:29:01,570 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9856 sequences
2026-04-12 02:29:01,570 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 39/39 [00:08<00:00,  4.50it/s]
2026-04-12 02:29:10,242 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 02:29:10,245 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 256]), labels=torch.Size([9856])
2026-04-12 02:29:10,279 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9308 sequences
2026-04-12 02:29:10,279 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 37/37 [00:08<00:00,  4.53it/s]
2026-04-12 02:29:18,457 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 02:29:18,457 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 256]), labels=torch.Size([9308])
2026-04-12 02:29:18,492 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:29:18,493 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 36/36 [00:07<00:00,  4.55it/s]
2026-04-12 02:29:26,417 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 02:29:26,417 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 256]), labels=torch.Size([9078])
2026-04-12 02:29:26,468 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:29:26,469 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 65/65 [00:14<00:00,  4.57it/s]
2026-04-12 02:29:40,733 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:29:40,734 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 256]), labels=torch.Size([16500])
2026-04-12 02:29:40,785 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:29:40,785 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 60/60 [00:12<00:00,  4.65it/s]
2026-04-12 02:29:53,706 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:29:53,707 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 256]), labels=torch.Size([15114])
2026-04-12 02:29:53,750 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:29:53,752 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 56/56 [00:12<00:00,  4.64it/s]
2026-04-12 02:30:05,834 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:30:05,834 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 256]), labels=torch.Size([14300])
2026-04-12 02:30:05,873 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:30:05,873 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 55/55 [00:11<00:00,  4.64it/s]
2026-04-12 02:30:17,728 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:30:17,728 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 256]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: DNABert_zhihan1996/DNABERT-2-117M

2026-04-12 02:30:18,220 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:18,247 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 02:30:18,509 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:18,545 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 02:30:18,814 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:18,845 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 02:30:19,122 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 02:30:19,402 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 02:30:19,685 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:19,735 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 02:30:19,735 - models - WARNING - zhihan1996/DNABERT-2-117M requires custom code; retrying config load with trust_remote_code=True
2026-04-12 02:30:20,010 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:20,036 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 02:30:20,308 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/configuration_bert.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:20,335 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/configuration_bert.py "HTTP/1.1 200 OK"
2026-04-12 02:30:20,607 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:20,635 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 02:30:20,902 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:20,931 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 02:30:21,238 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-04-12 02:30:21,244 - models - WARNING - Retrying zhihan1996/DNABERT-2-117M with low_cpu_mem_usage=False and ignore_mismatched_sizes=True to resolve meta-device tensors
2026-04-12 02:30:21,511 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M "HTTP/1.1 200 OK"
2026-04-12 02:30:21,577 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:21,605 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 02:30:21,853 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/main "HTTP/1.1 200 OK"
2026-04-12 02:30:21,883 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-04-12 02:30:21,893 - models - WARNING - Falling back to DNABERT MLM loader for zhihan1996/DNABERT-2-117M and using its backbone encoder
2026-04-12 02:30:22,159 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M "HTTP/1.1 200 OK"
2026-04-12 02:30:22,183 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 02:30:22,221 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:22,250 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 02:30:22,443 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/main "HTTP/1.1 200 OK"
2026-04-12 02:30:22,474 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/refs%2Fpr%2F40 "HTTP/1.1 200 OK"
2026-04-12 02:30:22,537 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-04-12 02:30:22,544 - models - WARNING - Final fallback: manual state_dict load for zhihan1996/DNABERT-2-117M to bypass meta tensors
2026-04-12 02:30:22,727 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 02:30:22,746 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-04-12 02:30:22,809 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M "HTTP/1.1 200 OK"
2026-04-12 02:30:22,865 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:30:22,903 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 02:30:23,011 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors "HTTP/1.1 302 Found"
2026-04-12 02:30:23,013 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/refs%2Fpr%2F40 "HTTP/1.1 200 OK"
2026-04-12 02:30:23,099 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/main "HTTP/1.1 200 OK"
2026-04-12 02:30:23,277 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-04-12 02:30:23,390 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 02:30:23,544 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
2026-04-12 02:30:23,544 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors "HTTP/1.1 302 Found"
2026-04-12 02:30:23,627 - models - WARNING - Manual load missing keys: 138
2026-04-12 02:30:23,627 - models - WARNING - Manual load unexpected keys: 142
2026-04-12 02:30:23,627 - models - INFO - Patched DNABERT remote flash attention in 2 module(s); using PyTorch attention path
2026-04-12 02:30:23,673 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/refs%2Fpr%2F40 "HTTP/1.1 200 OK"
2026-04-12 02:30:23,677 - models - INFO - Successfully loaded DNABert model: zhihan1996/DNABERT-2-117M
2026-04-12 02:30:23,944 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 26450 sequences
2026-04-12 02:30:23,944 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[FM] params=117,068,544 | param_mem_mb=446.58 | gflops_per_sample=18.1295 (measured_profiler)
[RUN ] gencode300_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings:   0%|          | 0/104 [00:00<?, ?it/s]2026-04-12 02:30:23,944 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors.index.json "HTTP/1.1 404 Not Found"
Extracting embeddings:   1%|          | 1/104 [00:00<00:22,  4.53it/s]2026-04-12 02:30:24,224 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors "HTTP/1.1 302 Found"
Extracting embeddings: 100%|██████████| 104/104 [00:18<00:00,  5.75it/s]
2026-04-12 02:30:42,123 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 02:30:42,123 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 768]), labels=torch.Size([26450])
2026-04-12 02:30:42,240 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 41262 sequences
2026-04-12 02:30:42,241 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gtex300_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 162/162 [00:28<00:00,  5.72it/s]
2026-04-12 02:31:10,668 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 02:31:10,668 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 768]), labels=torch.Size([41262])
2026-04-12 02:31:10,712 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 10752 sequences
2026-04-12 02:31:10,712 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gencode300_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 42/42 [00:07<00:00,  5.79it/s]
2026-04-12 02:31:18,005 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 02:31:18,005 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 768]), labels=torch.Size([10752])
2026-04-12 02:31:18,038 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9856 sequences
2026-04-12 02:31:18,039 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gencode300_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 39/39 [00:06<00:00,  5.77it/s]
2026-04-12 02:31:24,828 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 02:31:24,828 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 768]), labels=torch.Size([9856])
2026-04-12 02:31:24,876 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9308 sequences
2026-04-12 02:31:24,876 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gencode300_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 37/37 [00:06<00:00,  5.99it/s]
2026-04-12 02:31:31,088 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 02:31:31,088 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 768]), labels=torch.Size([9308])
2026-04-12 02:31:31,120 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9078 sequences
2026-04-12 02:31:31,122 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gencode300_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 36/36 [00:06<00:00,  5.76it/s]
2026-04-12 02:31:37,409 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 02:31:37,410 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 768]), labels=torch.Size([9078])
2026-04-12 02:31:37,469 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 16500 sequences
2026-04-12 02:31:37,469 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gtex300_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 65/65 [00:11<00:00,  5.74it/s]
2026-04-12 02:31:48,842 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:31:48,842 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 02:31:48,887 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 15114 sequences
2026-04-12 02:31:48,887 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gtex300_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 60/60 [00:10<00:00,  5.73it/s]
2026-04-12 02:31:59,413 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:31:59,413 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 02:31:59,456 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 14300 sequences
2026-04-12 02:31:59,456 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gtex300_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 56/56 [00:10<00:00,  5.49it/s]
2026-04-12 02:32:09,701 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:32:09,709 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 02:32:09,755 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 13974 sequences
2026-04-12 02:32:09,756 - splicing_embed_extract - INFO - Batch size: 256, FP16: False

[RUN ] gtex300_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 55/55 [00:09<00:00,  5.81it/s]
2026-04-12 02:32:19,265 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:32:19,265 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref

2026-04-12 02:32:19,728 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-500m-human-ref/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:32:19,762 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/f87b5d7233295242e79c951873d290f4cf992045/config.json "HTTP/1.1 200 OK"
2026-04-12 02:32:20,041 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-500m-human-ref/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:32:20,070 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/f87b5d7233295242e79c951873d290f4cf992045/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 02:32:20,342 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 02:32:20,623 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 02:32:20,893 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-500m-human-ref/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:32:20,922 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/f87b5d7233295242e79c951873d290f4cf992045/config.json "HTTP/1.1 200 OK"
2026-04-12 02:32:21,210 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-500m-human-ref/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

Loading weights:   0%|          | 0/390 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: InstaDeepAI/nucleotide-transformer-500m-human-ref
Key                         | Status     |
----------------------------+------------+-
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.decoder.weight      | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
2026-04-12 02:32:21,480 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-500m-human-ref "HTTP/1.1 200 OK"
2026-04-12 02:32:21,761 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/commits/main "HTTP/1.1 200 OK"
2026-04-12 02:32:22,063 - models - INFO - Successfully loaded NucleotideTransformer model: InstaDeepAI/nucleotide-transformer-500m-human-ref
2026-04-12 02:32:22,063 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 02:32:22,387 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-500m-human-ref/commits/refs%2Fpr%2F8 "HTTP/1.1 200 OK"
2026-04-12 02:32:22,395 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26450 sequences
2026-04-12 02:32:22,395 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[FM] params=480,438,241 | param_mem_mb=1832.73 | gflops_per_sample=48.4774 (measured_profiler)
[RUN ] gencode300_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings:   0%|          | 0/104 [00:00<?, ?it/s]2026-04-12 02:32:22,657 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-500m-human-ref/resolve/refs%2Fpr%2F8/model.safetensors.index.json "HTTP/1.1 404 Not Found"
Extracting embeddings:   1%|          | 1/104 [00:00<00:35,  2.94it/s]2026-04-12 02:32:22,938 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-500m-human-ref/resolve/refs%2Fpr%2F8/model.safetensors "HTTP/1.1 302 Found"
Extracting embeddings: 100%|██████████| 104/104 [00:26<00:00,  3.98it/s]
2026-04-12 02:32:48,621 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_embeddings.pt
2026-04-12 02:32:48,621 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 1280]), labels=torch.Size([26450])
2026-04-12 02:32:48,722 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41262 sequences
2026-04-12 02:32:48,724 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 162/162 [00:41<00:00,  3.95it/s]
2026-04-12 02:33:29,971 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_embeddings.pt
2026-04-12 02:33:29,976 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 1280]), labels=torch.Size([41262])
2026-04-12 02:33:30,020 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10752 sequences
2026-04-12 02:33:30,020 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 42/42 [00:10<00:00,  3.96it/s]
2026-04-12 02:33:40,688 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_10_embeddings.pt
2026-04-12 02:33:40,688 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 1280]), labels=torch.Size([10752])
2026-04-12 02:33:40,729 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9856 sequences
2026-04-12 02:33:40,729 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 39/39 [00:09<00:00,  4.01it/s]
2026-04-12 02:33:50,495 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_20_embeddings.pt
2026-04-12 02:33:50,495 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 1280]), labels=torch.Size([9856])
2026-04-12 02:33:50,532 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9308 sequences
2026-04-12 02:33:50,533 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 37/37 [00:09<00:00,  4.04it/s]
2026-04-12 02:33:59,726 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_50_embeddings.pt
2026-04-12 02:33:59,726 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 1280]), labels=torch.Size([9308])
2026-04-12 02:33:59,769 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:33:59,769 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 36/36 [00:08<00:00,  4.03it/s]
2026-04-12 02:34:08,763 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_100_embeddings.pt
2026-04-12 02:34:08,763 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 1280]), labels=torch.Size([9078])
2026-04-12 02:34:08,816 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:34:08,817 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 65/65 [00:16<00:00,  4.00it/s]
2026-04-12 02:34:25,130 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:34:25,138 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 1280]), labels=torch.Size([16500])
2026-04-12 02:34:25,192 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:34:25,192 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 60/60 [00:14<00:00,  4.04it/s]
2026-04-12 02:34:40,137 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:34:40,138 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 1280]), labels=torch.Size([15114])
2026-04-12 02:34:40,189 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:34:40,189 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 56/56 [00:14<00:00,  3.98it/s]
2026-04-12 02:34:54,342 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:34:54,342 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 1280]), labels=torch.Size([14300])
2026-04-12 02:34:54,406 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:34:54,406 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 55/55 [00:13<00:00,  4.00it/s]
2026-04-12 02:35:08,207 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:35:08,207 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 1280]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species

2026-04-12 02:35:08,691 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:08,718 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/config.json "HTTP/1.1 200 OK"
2026-04-12 02:35:08,980 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/esm_config.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:09,007 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/esm_config.py "HTTP/1.1 200 OK"
2026-04-12 02:35:09,305 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:09,335 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/config.json "HTTP/1.1 200 OK"
2026-04-12 02:35:09,607 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:09,637 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 02:35:09,907 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 02:35:10,180 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 02:35:10,447 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:10,487 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/config.json "HTTP/1.1 200 OK"
2026-04-12 02:35:10,745 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/esm_config.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:10,777 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/esm_config.py "HTTP/1.1 200 OK"
2026-04-12 02:35:11,045 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:35:11,076 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/f34324c6fde36a4f635f0f1f06cac5d25acd6798/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/335 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
Key                                              | Status     |
-------------------------------------------------+------------+---------------------------------------------------------------------------------------------
lm_head.layer_norm.weight                        | UNEXPECTED |
lm_head.dense.weight                             | UNEXPECTED |
lm_head.decoder.weight                           | UNEXPECTED |
lm_head.dense.bias                               | UNEXPECTED |
lm_head.bias                                     | UNEXPECTED |
lm_head.layer_norm.bias                          | UNEXPECTED |
encoder.layer.{0...21}.intermediate.dense.bias   | MISSING    |
encoder.layer.{0...21}.output.dense.bias         | MISSING    |
pooler.dense.bias                                | MISSING    |
pooler.dense.weight                              | MISSING    |
encoder.layer.{0...21}.intermediate.dense.weight | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([4096, 512]) vs model:torch.Size([2048, 512])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.
2026-04-12 02:35:11,364 - models - WARNING - Retrying InstaDeepAI/nucleotide-transformer-v2-100m-multi-species with ignore_mismatched_sizes=True due to checkpoint/model shape mismatch

Loading weights:   0%|          | 0/335 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
Key                                              | Status     |
-------------------------------------------------+------------+---------------------------------------------------------------------------------------------
lm_head.layer_norm.weight                        | UNEXPECTED |
lm_head.dense.weight                             | UNEXPECTED |
lm_head.decoder.weight                           | UNEXPECTED |
lm_head.dense.bias                               | UNEXPECTED |
lm_head.bias                                     | UNEXPECTED |
lm_head.layer_norm.bias                          | UNEXPECTED |
encoder.layer.{0...21}.intermediate.dense.bias   | MISSING    |
encoder.layer.{0...21}.output.dense.bias         | MISSING    |
pooler.dense.bias                                | MISSING    |
pooler.dense.weight                              | MISSING    |
encoder.layer.{0...21}.intermediate.dense.weight | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([4096, 512]) vs model:torch.Size([2048, 512])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.
2026-04-12 02:35:11,739 - models - INFO - Successfully loaded NucleotideTransformer model: InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
2026-04-12 02:35:12,112 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26450 sequences
2026-04-12 02:35:12,112 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[FM] params=71,719,265 | param_mem_mb=273.59 | gflops_per_sample=7.1897 (measured_profiler)
[RUN ] gencode300_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 104/104 [00:11<00:00,  9.43it/s]
2026-04-12 02:35:23,196 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_embeddings.pt
2026-04-12 02:35:23,197 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 512]), labels=torch.Size([26450])
2026-04-12 02:35:23,278 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41262 sequences
2026-04-12 02:35:23,280 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 162/162 [00:17<00:00,  9.21it/s]
2026-04-12 02:35:40,949 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_embeddings.pt
2026-04-12 02:35:40,949 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 512]), labels=torch.Size([41262])
2026-04-12 02:35:40,982 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10752 sequences
2026-04-12 02:35:40,982 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 42/42 [00:04<00:00,  9.52it/s]
2026-04-12 02:35:45,404 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 02:35:45,404 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 512]), labels=torch.Size([10752])
2026-04-12 02:35:45,443 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9856 sequences
2026-04-12 02:35:45,444 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 39/39 [00:04<00:00,  9.35it/s]
2026-04-12 02:35:49,641 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 02:35:49,642 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 512]), labels=torch.Size([9856])
2026-04-12 02:35:49,668 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9308 sequences
2026-04-12 02:35:49,668 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 37/37 [00:03<00:00,  9.53it/s]
2026-04-12 02:35:53,578 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 02:35:53,579 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 512]), labels=torch.Size([9308])
2026-04-12 02:35:53,603 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:35:53,604 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 36/36 [00:03<00:00,  9.48it/s]
2026-04-12 02:35:57,422 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 02:35:57,422 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 512]), labels=torch.Size([9078])
2026-04-12 02:35:57,467 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:35:57,467 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 65/65 [00:06<00:00,  9.41it/s]
2026-04-12 02:36:04,408 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:36:04,408 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 512]), labels=torch.Size([16500])
2026-04-12 02:36:04,450 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:36:04,457 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 60/60 [00:06<00:00,  9.47it/s]
2026-04-12 02:36:10,828 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:36:10,828 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 512]), labels=torch.Size([15114])
2026-04-12 02:36:10,865 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:36:10,866 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 56/56 [00:05<00:00,  9.48it/s]
2026-04-12 02:36:16,804 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:36:16,804 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 512]), labels=torch.Size([14300])
2026-04-12 02:36:16,841 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:36:16,842 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 55/55 [00:05<00:00,  9.40it/s]
2026-04-12 02:36:22,725 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:36:22,726 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 512]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species

2026-04-12 02:36:23,226 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:23,293 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/config.json "HTTP/1.1 200 OK"
2026-04-12 02:36:23,569 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/esm_config.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:23,862 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/esm_config.py "HTTP/1.1 200 OK"
2026-04-12 02:36:24,169 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:24,198 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/config.json "HTTP/1.1 200 OK"
2026-04-12 02:36:24,470 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:24,531 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 02:36:24,845 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 02:36:25,182 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 02:36:25,447 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:25,479 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/config.json "HTTP/1.1 200 OK"
2026-04-12 02:36:25,753 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/esm_config.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:25,783 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/esm_config.py "HTTP/1.1 200 OK"
2026-04-12 02:36:26,057 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 02:36:26,085 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/c0f0359229f36ff6bc3a021247eefe0a9c344bd1/config.json "HTTP/1.1 200 OK"
2026-04-12 02:36:26,347 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

Loading weights:   0%|          | 0/365 [00:00<?, ?it/s]

2026-04-12 02:36:26,625 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species "HTTP/1.1 200 OK"
EsmModel LOAD REPORT from: InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
Key                                              | Status     |
-------------------------------------------------+------------+---------------------------------------------------------------------------------------------
lm_head.layer_norm.weight                        | UNEXPECTED |
lm_head.dense.weight                             | UNEXPECTED |
lm_head.decoder.weight                           | UNEXPECTED |
lm_head.dense.bias                               | UNEXPECTED |
lm_head.bias                                     | UNEXPECTED |
lm_head.layer_norm.bias                          | UNEXPECTED |
encoder.layer.{0...23}.intermediate.dense.bias   | MISSING    |
encoder.layer.{0...23}.output.dense.bias         | MISSING    |
pooler.dense.bias                                | MISSING    |
pooler.dense.weight                              | MISSING    |
encoder.layer.{0...23}.intermediate.dense.weight | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([6144, 768]) vs model:torch.Size([3072, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.
2026-04-12 02:36:26,711 - models - WARNING - Retrying InstaDeepAI/nucleotide-transformer-v2-250m-multi-species with ignore_mismatched_sizes=True due to checkpoint/model shape mismatch
2026-04-12 02:36:26,906 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/commits/main "HTTP/1.1 200 OK"
2026-04-12 02:36:27,082 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

Loading weights:   0%|          | 0/365 [00:00<?, ?it/s]

2026-04-12 02:36:27,193 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 02:36:27,349 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species "HTTP/1.1 200 OK"
EsmModel LOAD REPORT from: InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
Key                                              | Status     |
-------------------------------------------------+------------+---------------------------------------------------------------------------------------------
lm_head.layer_norm.weight                        | UNEXPECTED |
lm_head.dense.weight                             | UNEXPECTED |
lm_head.decoder.weight                           | UNEXPECTED |
lm_head.dense.bias                               | UNEXPECTED |
lm_head.bias                                     | UNEXPECTED |
lm_head.layer_norm.bias                          | UNEXPECTED |
encoder.layer.{0...23}.intermediate.dense.bias   | MISSING    |
encoder.layer.{0...23}.output.dense.bias         | MISSING    |
pooler.dense.bias                                | MISSING    |
pooler.dense.weight                              | MISSING    |
encoder.layer.{0...23}.intermediate.dense.weight | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([6144, 768]) vs model:torch.Size([3072, 768])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.
2026-04-12 02:36:27,531 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/commits/refs%2Fpr%2F3 "HTTP/1.1 200 OK"
2026-04-12 02:36:27,632 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/commits/main "HTTP/1.1 200 OK"
2026-04-12 02:36:27,798 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/refs%2Fpr%2F3/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-04-12 02:36:27,885 - models - INFO - Successfully loaded NucleotideTransformer model: InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
2026-04-12 02:36:27,908 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 02:36:28,083 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/refs%2Fpr%2F3/model.safetensors "HTTP/1.1 302 Found"
2026-04-12 02:36:28,206 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/commits/refs%2Fpr%2F3 "HTTP/1.1 200 OK"
2026-04-12 02:36:28,281 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26450 sequences
2026-04-12 02:36:28,281 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[FM] params=173,855,617 | param_mem_mb=663.21 | gflops_per_sample=17.5404 (measured_profiler)
[RUN ] gencode300_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings:   0%|          | 0/104 [00:00<?, ?it/s]2026-04-12 02:36:28,499 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/refs%2Fpr%2F3/model.safetensors.index.json "HTTP/1.1 404 Not Found"
Extracting embeddings:   2%|▏         | 2/104 [00:00<00:19,  5.34it/s]2026-04-12 02:36:28,765 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-250m-multi-species/resolve/refs%2Fpr%2F3/model.safetensors "HTTP/1.1 302 Found"
Extracting embeddings: 100%|██████████| 104/104 [00:16<00:00,  6.26it/s]
2026-04-12 02:36:44,964 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_embeddings.pt
2026-04-12 02:36:44,965 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 768]), labels=torch.Size([26450])
2026-04-12 02:36:45,056 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41262 sequences
2026-04-12 02:36:45,057 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 162/162 [00:26<00:00,  6.17it/s]
2026-04-12 02:37:11,434 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_embeddings.pt
2026-04-12 02:37:11,434 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 768]), labels=torch.Size([41262])
2026-04-12 02:37:11,464 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10752 sequences
2026-04-12 02:37:11,464 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 42/42 [00:06<00:00,  6.12it/s]
2026-04-12 02:37:18,363 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 02:37:18,363 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 768]), labels=torch.Size([10752])
2026-04-12 02:37:18,393 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9856 sequences
2026-04-12 02:37:18,394 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 39/39 [00:06<00:00,  6.22it/s]
2026-04-12 02:37:24,692 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 02:37:24,693 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 768]), labels=torch.Size([9856])
2026-04-12 02:37:24,719 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9308 sequences
2026-04-12 02:37:24,719 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 37/37 [00:05<00:00,  6.22it/s]
2026-04-12 02:37:30,699 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 02:37:30,701 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 768]), labels=torch.Size([9308])
2026-04-12 02:37:30,729 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:37:30,729 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gencode300_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 36/36 [00:05<00:00,  6.23it/s]
2026-04-12 02:37:36,537 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 02:37:36,537 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 768]), labels=torch.Size([9078])
2026-04-12 02:37:36,576 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:37:36,576 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 65/65 [00:10<00:00,  6.23it/s]
2026-04-12 02:37:47,057 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:37:47,059 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 02:37:47,102 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:37:47,102 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 60/60 [00:09<00:00,  6.37it/s]
2026-04-12 02:37:56,565 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:37:56,571 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 02:37:56,607 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:37:56,607 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 56/56 [00:08<00:00,  6.23it/s]
2026-04-12 02:38:05,635 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:38:05,635 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 02:38:05,673 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:38:05,674 - splicing_embed_extract - INFO - Batch size: 256, FP16: True

[RUN ] gtex300_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 55/55 [00:08<00:00,  6.14it/s]
2026-04-12 02:38:14,672 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:38:14,672 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

====================================================================================================
WINDOW 600
[RAW ] gencode600_test_set_1_1_raw.csv
[RAW ] gtex600_test_set_1_1_raw.csv

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
[FM] params=3,277,568 | param_mem_mb=12.50 | gflops_per_sample=3.8999 (measured_profiler)
[RUN ] gencode600_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 02:38:17,889 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26401 sequences
2026-04-12 02:38:17,889 - splicing_embed_extract - INFO - Batch size: 128, FP16: True
Extracting embeddings: 100%|██████████| 207/207 [00:39<00:00,  5.26it/s]
2026-04-12 02:38:57,251 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_embeddings.pt
2026-04-12 02:38:57,252 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 256]), labels=torch.Size([26401])
2026-04-12 02:38:57,400 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41261 sequences
2026-04-12 02:38:57,401 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 323/323 [01:01<00:00,  5.23it/s]
2026-04-12 02:39:59,212 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 02:39:59,216 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 256]), labels=torch.Size([41261])
2026-04-12 02:39:59,267 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10692 sequences
2026-04-12 02:39:59,267 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 84/84 [00:15<00:00,  5.32it/s]
2026-04-12 02:40:15,054 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 02:40:15,054 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 256]), labels=torch.Size([10692])
2026-04-12 02:40:15,106 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9790 sequences
2026-04-12 02:40:15,106 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 77/77 [00:14<00:00,  5.36it/s]
2026-04-12 02:40:29,481 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 02:40:29,481 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 256]), labels=torch.Size([9790])
2026-04-12 02:40:29,526 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9256 sequences
2026-04-12 02:40:29,526 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 73/73 [00:13<00:00,  5.40it/s]
2026-04-12 02:40:43,047 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 02:40:43,047 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 256]), labels=torch.Size([9256])
2026-04-12 02:40:43,092 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:40:43,092 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 71/71 [00:13<00:00,  5.31it/s]
2026-04-12 02:40:56,467 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 02:40:56,468 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 256]), labels=torch.Size([9078])
2026-04-12 02:40:56,545 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:40:56,546 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 129/129 [00:24<00:00,  5.32it/s]
2026-04-12 02:41:20,804 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:41:20,804 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 256]), labels=torch.Size([16500])
2026-04-12 02:41:20,869 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:41:20,869 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 119/119 [00:22<00:00,  5.38it/s]
2026-04-12 02:41:42,977 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:41:42,978 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 256]), labels=torch.Size([15114])
2026-04-12 02:41:43,042 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:41:43,042 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 112/112 [00:20<00:00,  5.37it/s]
2026-04-12 02:42:03,905 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:42:03,905 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 256]), labels=torch.Size([14300])
2026-04-12 02:42:03,975 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:42:03,975 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 110/110 [00:20<00:00,  5.41it/s]
2026-04-12 02:42:24,324 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:42:24,326 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 256]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
[FM] params=6,550,528 | param_mem_mb=24.99 | gflops_per_sample=7.7998 (measured_profiler)
[RUN ] gencode600_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 02:42:24,667 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26401 sequences
2026-04-12 02:42:24,667 - splicing_embed_extract - INFO - Batch size: 128, FP16: True
Extracting embeddings: 100%|██████████| 207/207 [00:44<00:00,  4.64it/s]
2026-04-12 02:43:09,341 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_embeddings.pt
2026-04-12 02:43:09,342 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 256]), labels=torch.Size([26401])
2026-04-12 02:43:09,503 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41261 sequences
2026-04-12 02:43:09,504 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 323/323 [01:10<00:00,  4.60it/s]
2026-04-12 02:44:19,709 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 02:44:19,709 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 256]), labels=torch.Size([41261])
2026-04-12 02:44:19,780 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10692 sequences
2026-04-12 02:44:19,781 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 84/84 [00:18<00:00,  4.61it/s]
2026-04-12 02:44:38,014 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 02:44:38,016 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 256]), labels=torch.Size([10692])
2026-04-12 02:44:38,069 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9790 sequences
2026-04-12 02:44:38,071 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 77/77 [00:16<00:00,  4.63it/s]
2026-04-12 02:44:54,725 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 02:44:54,725 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 256]), labels=torch.Size([9790])
2026-04-12 02:44:54,779 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9256 sequences
2026-04-12 02:44:54,784 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 73/73 [00:15<00:00,  4.62it/s]
2026-04-12 02:45:10,598 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 02:45:10,598 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 256]), labels=torch.Size([9256])
2026-04-12 02:45:10,646 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:45:10,646 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 71/71 [00:15<00:00,  4.54it/s]
2026-04-12 02:45:26,294 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 02:45:26,295 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 256]), labels=torch.Size([9078])
2026-04-12 02:45:26,369 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:45:26,371 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 129/129 [00:28<00:00,  4.58it/s]
2026-04-12 02:45:54,558 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:45:54,559 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 256]), labels=torch.Size([16500])
2026-04-12 02:45:54,632 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:45:54,634 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 119/119 [00:25<00:00,  4.65it/s]
2026-04-12 02:46:20,263 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:46:20,263 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 256]), labels=torch.Size([15114])
2026-04-12 02:46:20,334 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:46:20,334 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 112/112 [00:24<00:00,  4.61it/s]
2026-04-12 02:46:44,652 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:46:44,653 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 256]), labels=torch.Size([14300])
2026-04-12 02:46:44,735 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:46:44,735 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 110/110 [00:23<00:00,  4.61it/s]
2026-04-12 02:47:08,582 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:47:08,583 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 256]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: DNABert_zhihan1996/DNABERT-2-117M
[FM] params=117,068,544 | param_mem_mb=446.58 | gflops_per_sample=35.7673 (measured_profiler)
[RUN ] gencode600_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 02:47:08,915 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 26401 sequences
2026-04-12 02:47:08,915 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 207/207 [00:35<00:00,  5.89it/s]
2026-04-12 02:47:44,132 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 02:47:44,132 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 768]), labels=torch.Size([26401])
2026-04-12 02:47:44,281 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 41261 sequences
2026-04-12 02:47:44,283 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gtex600_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 323/323 [00:54<00:00,  5.91it/s]
2026-04-12 02:48:39,084 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 02:48:39,084 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 768]), labels=torch.Size([41261])
2026-04-12 02:48:39,146 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 10692 sequences
2026-04-12 02:48:39,148 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gencode600_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 84/84 [00:14<00:00,  5.92it/s]
2026-04-12 02:48:53,362 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 02:48:53,363 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 768]), labels=torch.Size([10692])
2026-04-12 02:48:53,408 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9790 sequences
2026-04-12 02:48:53,408 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gencode600_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 77/77 [00:12<00:00,  5.94it/s]
2026-04-12 02:49:06,394 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 02:49:06,394 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 768]), labels=torch.Size([9790])
2026-04-12 02:49:06,441 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9256 sequences
2026-04-12 02:49:06,441 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gencode600_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 73/73 [00:12<00:00,  5.96it/s]
2026-04-12 02:49:18,705 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 02:49:18,705 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 768]), labels=torch.Size([9256])
2026-04-12 02:49:18,747 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9078 sequences
2026-04-12 02:49:18,747 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gencode600_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 71/71 [00:11<00:00,  5.92it/s]
2026-04-12 02:49:30,774 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 02:49:30,774 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 768]), labels=torch.Size([9078])
2026-04-12 02:49:30,849 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 16500 sequences
2026-04-12 02:49:30,849 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gtex600_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 129/129 [00:21<00:00,  5.94it/s]
2026-04-12 02:49:52,624 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:49:52,624 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 02:49:52,699 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 15114 sequences
2026-04-12 02:49:52,699 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gtex600_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 119/119 [00:19<00:00,  5.98it/s]
2026-04-12 02:50:12,651 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:50:12,651 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 02:50:12,726 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 14300 sequences
2026-04-12 02:50:12,728 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gtex600_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 112/112 [00:18<00:00,  5.92it/s]
2026-04-12 02:50:31,690 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:50:31,690 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 02:50:31,759 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 13974 sequences
2026-04-12 02:50:31,759 - splicing_embed_extract - INFO - Batch size: 128, FP16: False

[RUN ] gtex600_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 110/110 [00:18<00:00,  5.96it/s]
2026-04-12 02:50:50,252 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:50:50,254 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref

2026-04-12 02:50:50,699 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26401 sequences
2026-04-12 02:50:50,700 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[FM] params=480,438,241 | param_mem_mb=1832.73 | gflops_per_sample=96.6240 (measured_profiler)
[RUN ] gencode600_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 207/207 [00:50<00:00,  4.09it/s]
2026-04-12 02:51:41,431 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_embeddings.pt
2026-04-12 02:51:41,431 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 1280]), labels=torch.Size([26401])
2026-04-12 02:51:41,585 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41261 sequences
2026-04-12 02:51:41,586 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 323/323 [01:18<00:00,  4.09it/s]
2026-04-12 02:53:00,739 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_embeddings.pt
2026-04-12 02:53:00,739 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 1280]), labels=torch.Size([41261])
2026-04-12 02:53:00,780 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10692 sequences
2026-04-12 02:53:00,780 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 84/84 [00:20<00:00,  4.11it/s]
2026-04-12 02:53:21,271 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_10_embeddings.pt
2026-04-12 02:53:21,273 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 1280]), labels=torch.Size([10692])
2026-04-12 02:53:21,318 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9790 sequences
2026-04-12 02:53:21,318 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 77/77 [00:18<00:00,  4.11it/s]
2026-04-12 02:53:40,099 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_20_embeddings.pt
2026-04-12 02:53:40,100 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 1280]), labels=torch.Size([9790])
2026-04-12 02:53:40,148 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9256 sequences
2026-04-12 02:53:40,148 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 73/73 [00:17<00:00,  4.12it/s]
2026-04-12 02:53:57,935 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_50_embeddings.pt
2026-04-12 02:53:57,935 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 1280]), labels=torch.Size([9256])
2026-04-12 02:53:57,984 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:53:57,984 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 71/71 [00:17<00:00,  4.09it/s]
2026-04-12 02:54:15,395 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_100_embeddings.pt
2026-04-12 02:54:15,395 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 1280]), labels=torch.Size([9078])
2026-04-12 02:54:15,466 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:54:15,466 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 129/129 [00:31<00:00,  4.09it/s]
2026-04-12 02:54:47,093 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:54:47,093 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 1280]), labels=torch.Size([16500])
2026-04-12 02:54:47,170 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:54:47,174 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 119/119 [00:28<00:00,  4.11it/s]
2026-04-12 02:55:16,174 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:55:16,176 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 1280]), labels=torch.Size([15114])
2026-04-12 02:55:16,245 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:55:16,245 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 112/112 [00:27<00:00,  4.09it/s]
2026-04-12 02:55:43,720 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:55:43,720 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 1280]), labels=torch.Size([14300])
2026-04-12 02:55:43,787 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:55:43,790 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 110/110 [00:26<00:00,  4.11it/s]
2026-04-12 02:56:10,645 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:56:10,647 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 1280]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species

2026-04-12 02:56:11,174 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26401 sequences
2026-04-12 02:56:11,174 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[FM] params=71,719,265 | param_mem_mb=273.59 | gflops_per_sample=14.4672 (measured_profiler)
[RUN ] gencode600_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 207/207 [00:22<00:00,  9.35it/s]
2026-04-12 02:56:33,361 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_embeddings.pt
2026-04-12 02:56:33,365 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 512]), labels=torch.Size([26401])
2026-04-12 02:56:33,518 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41261 sequences
2026-04-12 02:56:33,518 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 323/323 [00:34<00:00,  9.33it/s]
2026-04-12 02:57:08,208 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_embeddings.pt
2026-04-12 02:57:08,208 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 512]), labels=torch.Size([41261])
2026-04-12 02:57:08,269 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10692 sequences
2026-04-12 02:57:08,271 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 84/84 [00:08<00:00,  9.36it/s]
2026-04-12 02:57:17,282 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 02:57:17,282 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 512]), labels=torch.Size([10692])
2026-04-12 02:57:17,330 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9790 sequences
2026-04-12 02:57:17,330 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 77/77 [00:08<00:00,  9.37it/s]
2026-04-12 02:57:25,570 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 02:57:25,570 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 512]), labels=torch.Size([9790])
2026-04-12 02:57:25,607 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9256 sequences
2026-04-12 02:57:25,610 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 73/73 [00:07<00:00,  9.39it/s]
2026-04-12 02:57:33,405 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 02:57:33,405 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 512]), labels=torch.Size([9256])
2026-04-12 02:57:33,445 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 02:57:33,445 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 71/71 [00:07<00:00,  9.25it/s]
2026-04-12 02:57:41,148 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 02:57:41,148 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 512]), labels=torch.Size([9078])
2026-04-12 02:57:41,225 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 02:57:41,225 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 129/129 [00:13<00:00,  9.33it/s]
2026-04-12 02:57:55,079 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 02:57:55,079 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 512]), labels=torch.Size([16500])
2026-04-12 02:57:55,156 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 02:57:55,156 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 119/119 [00:12<00:00,  9.38it/s]
2026-04-12 02:58:07,868 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 02:58:07,869 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 512]), labels=torch.Size([15114])
2026-04-12 02:58:07,945 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 02:58:07,945 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 112/112 [00:11<00:00,  9.37it/s]
2026-04-12 02:58:19,936 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 02:58:19,936 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 512]), labels=torch.Size([14300])
2026-04-12 02:58:20,004 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 02:58:20,004 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 110/110 [00:11<00:00,  9.39it/s]
2026-04-12 02:58:31,750 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 02:58:31,750 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 512]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species

2026-04-12 02:58:32,312 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26401 sequences
2026-04-12 02:58:32,313 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[FM] params=173,855,617 | param_mem_mb=663.21 | gflops_per_sample=35.1099 (measured_profiler)
[RUN ] gencode600_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 207/207 [00:32<00:00,  6.36it/s]
2026-04-12 02:59:04,925 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_embeddings.pt
2026-04-12 02:59:04,925 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 768]), labels=torch.Size([26401])
2026-04-12 02:59:05,091 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41261 sequences
2026-04-12 02:59:05,091 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

Extracting embeddings: 100%|██████████| 323/323 [00:50<00:00,  6.36it/s]
2026-04-12 02:59:56,033 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_embeddings.pt
2026-04-12 02:59:56,033 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 768]), labels=torch.Size([41261])
2026-04-12 02:59:56,087 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10692 sequences
2026-04-12 02:59:56,087 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 84/84 [00:13<00:00,  6.35it/s]
2026-04-12 03:00:09,357 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 03:00:09,357 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 768]), labels=torch.Size([10692])
2026-04-12 03:00:09,389 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9790 sequences
2026-04-12 03:00:09,389 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 77/77 [00:12<00:00,  6.34it/s]
2026-04-12 03:00:21,568 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 03:00:21,568 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 768]), labels=torch.Size([9790])
2026-04-12 03:00:21,607 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9256 sequences
2026-04-12 03:00:21,607 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 73/73 [00:11<00:00,  6.35it/s]
2026-04-12 03:00:33,125 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 03:00:33,125 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 768]), labels=torch.Size([9256])
2026-04-12 03:00:33,172 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 03:00:33,172 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gencode600_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 71/71 [00:11<00:00,  6.32it/s]
2026-04-12 03:00:44,427 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 03:00:44,427 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 768]), labels=torch.Size([9078])
2026-04-12 03:00:44,485 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 03:00:44,485 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 129/129 [00:20<00:00,  6.31it/s]
2026-04-12 03:01:04,992 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:01:04,992 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 03:01:05,055 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 03:01:05,055 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 119/119 [00:18<00:00,  6.37it/s]
2026-04-12 03:01:23,788 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:01:23,797 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 03:01:23,857 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 03:01:23,857 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 112/112 [00:17<00:00,  6.35it/s]
2026-04-12 03:01:41,548 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:01:41,548 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 03:01:41,615 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 03:01:41,616 - splicing_embed_extract - INFO - Batch size: 128, FP16: True

[RUN ] gtex600_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 110/110 [00:17<00:00,  6.36it/s]
2026-04-12 03:01:58,971 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:01:58,972 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

====================================================================================================
WINDOW 1000
[RAW ] gencode1000_test_set_1_1_raw.csv
[RAW ] gtex1000_test_set_1_1_raw.csv

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
[FM] params=3,277,568 | param_mem_mb=12.50 | gflops_per_sample=6.4998 (measured_profiler)
[RUN ] gencode1000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 03:02:04,018 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26315 sequences
2026-04-12 03:02:04,018 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 412/412 [01:03<00:00,  6.49it/s]
2026-04-12 03:03:07,558 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_embeddings.pt
2026-04-12 03:03:07,558 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 256]), labels=torch.Size([26315])

[RUN ] gtex1000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:03:07,769 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41258 sequences
2026-04-12 03:03:07,769 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 645/645 [01:39<00:00,  6.51it/s]
2026-04-12 03:04:46,887 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 03:04:46,887 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 256]), labels=torch.Size([41258])
2026-04-12 03:04:46,964 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10584 sequences
2026-04-12 03:04:46,964 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 166/166 [00:25<00:00,  6.46it/s]
2026-04-12 03:05:12,685 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 03:05:12,685 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 256]), labels=torch.Size([10584])
2026-04-12 03:05:12,744 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9702 sequences
2026-04-12 03:05:12,744 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 152/152 [00:23<00:00,  6.49it/s]
2026-04-12 03:05:36,169 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 03:05:36,169 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 256]), labels=torch.Size([9702])
2026-04-12 03:05:36,229 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9152 sequences
2026-04-12 03:05:36,234 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 143/143 [00:22<00:00,  6.43it/s]
2026-04-12 03:05:58,485 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 03:05:58,487 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 256]), labels=torch.Size([9152])
2026-04-12 03:05:58,558 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 03:05:58,558 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 141/141 [00:22<00:00,  6.41it/s]
2026-04-12 03:06:20,575 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 03:06:20,575 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 256]), labels=torch.Size([8976])
2026-04-12 03:06:20,675 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 03:06:20,676 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 258/258 [00:39<00:00,  6.49it/s]
2026-04-12 03:07:00,455 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:07:00,455 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 256]), labels=torch.Size([16500])
2026-04-12 03:07:00,546 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 03:07:00,546 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 237/237 [00:36<00:00,  6.47it/s]
2026-04-12 03:07:37,189 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:07:37,189 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 256]), labels=torch.Size([15114])
2026-04-12 03:07:37,280 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 03:07:37,280 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 224/224 [00:34<00:00,  6.54it/s]
2026-04-12 03:08:11,521 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:08:11,521 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 256]), labels=torch.Size([14300])
2026-04-12 03:08:11,608 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 03:08:11,608 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 219/219 [00:33<00:00,  6.45it/s]
2026-04-12 03:08:45,580 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:08:45,580 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 256]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
[FM] params=6,550,528 | param_mem_mb=24.99 | gflops_per_sample=12.9997 (measured_profiler)
[RUN ] gencode1000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 03:08:45,969 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26315 sequences
2026-04-12 03:08:45,969 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 412/412 [01:10<00:00,  5.81it/s]
2026-04-12 03:09:56,941 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_embeddings.pt
2026-04-12 03:09:56,941 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 256]), labels=torch.Size([26315])

[RUN ] gtex1000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:09:57,166 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41258 sequences
2026-04-12 03:09:57,167 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 645/645 [02:16<00:00,  4.74it/s]
2026-04-12 03:12:13,328 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 03:12:13,329 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 256]), labels=torch.Size([41258])
2026-04-12 03:12:13,417 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10584 sequences
2026-04-12 03:12:13,417 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 166/166 [00:35<00:00,  4.66it/s]
2026-04-12 03:12:49,063 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 03:12:49,063 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 256]), labels=torch.Size([10584])
2026-04-12 03:12:49,132 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9702 sequences
2026-04-12 03:12:49,132 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 152/152 [00:32<00:00,  4.63it/s]
2026-04-12 03:13:22,013 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 03:13:22,013 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 256]), labels=torch.Size([9702])
2026-04-12 03:13:22,091 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9152 sequences
2026-04-12 03:13:22,093 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 143/143 [00:30<00:00,  4.66it/s]
2026-04-12 03:13:52,819 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 03:13:52,820 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 256]), labels=torch.Size([9152])
2026-04-12 03:13:52,901 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 03:13:52,902 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 141/141 [00:30<00:00,  4.65it/s]
2026-04-12 03:14:23,212 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 03:14:23,213 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 256]), labels=torch.Size([8976])
2026-04-12 03:14:23,326 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 03:14:23,327 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 258/258 [00:55<00:00,  4.66it/s]
2026-04-12 03:15:18,756 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:15:18,757 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 256]), labels=torch.Size([16500])
2026-04-12 03:15:18,881 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 03:15:18,881 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 237/237 [00:50<00:00,  4.65it/s]
2026-04-12 03:16:09,815 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:16:09,815 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 256]), labels=torch.Size([15114])
2026-04-12 03:16:09,921 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 03:16:09,922 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 224/224 [00:48<00:00,  4.64it/s]
2026-04-12 03:16:58,196 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:16:58,197 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 256]), labels=torch.Size([14300])
2026-04-12 03:16:58,305 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 03:16:58,305 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 219/219 [00:47<00:00,  4.65it/s]
2026-04-12 03:17:45,414 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:17:45,415 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 256]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: DNABert_zhihan1996/DNABERT-2-117M
[FM] params=117,068,544 | param_mem_mb=446.58 | gflops_per_sample=59.9321 (measured_profiler)
[RUN ] gencode1000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 03:17:45,833 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 26315 sequences
2026-04-12 03:17:45,835 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 412/412 [01:00<00:00,  6.80it/s]
2026-04-12 03:18:46,532 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 03:18:46,533 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 768]), labels=torch.Size([26315])

[RUN ] gtex1000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:18:46,801 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 41258 sequences
2026-04-12 03:18:46,801 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 645/645 [01:34<00:00,  6.81it/s]
2026-04-12 03:20:21,623 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 03:20:21,624 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 768]), labels=torch.Size([41258])
2026-04-12 03:20:21,710 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 10584 sequences
2026-04-12 03:20:21,710 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gencode1000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 166/166 [00:24<00:00,  6.81it/s]
2026-04-12 03:20:46,120 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 03:20:46,120 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 768]), labels=torch.Size([10584])
2026-04-12 03:20:46,205 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9702 sequences
2026-04-12 03:20:46,207 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gencode1000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 152/152 [00:22<00:00,  6.81it/s]
2026-04-12 03:21:08,548 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 03:21:08,548 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 768]), labels=torch.Size([9702])
2026-04-12 03:21:08,636 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9152 sequences
2026-04-12 03:21:08,636 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gencode1000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 143/143 [00:21<00:00,  6.80it/s]
2026-04-12 03:21:29,705 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 03:21:29,705 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 768]), labels=torch.Size([9152])
2026-04-12 03:21:29,786 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 8976 sequences
2026-04-12 03:21:29,787 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gencode1000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 141/141 [00:20<00:00,  6.82it/s]
2026-04-12 03:21:50,490 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 03:21:50,490 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 03:21:50,624 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 16500 sequences
2026-04-12 03:21:50,625 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gtex1000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 258/258 [00:37<00:00,  6.82it/s]
2026-04-12 03:22:28,520 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:22:28,522 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 03:22:28,645 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 15114 sequences
2026-04-12 03:22:28,645 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gtex1000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 237/237 [00:34<00:00,  6.84it/s]
2026-04-12 03:23:03,361 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:23:03,361 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 03:23:03,474 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 14300 sequences
2026-04-12 03:23:03,476 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gtex1000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 224/224 [00:32<00:00,  6.83it/s]
2026-04-12 03:23:36,311 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:23:36,311 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 03:23:36,424 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 13974 sequences
2026-04-12 03:23:36,425 - splicing_embed_extract - INFO - Batch size: 64, FP16: False

[RUN ] gtex1000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 219/219 [00:32<00:00,  6.83it/s]
2026-04-12 03:24:08,527 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:24:08,527 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref

2026-04-12 03:24:09,089 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26315 sequences
2026-04-12 03:24:09,090 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[FM] params=480,438,241 | param_mem_mb=1832.73 | gflops_per_sample=165.0655 (measured_profiler)
[RUN ] gencode1000_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 412/412 [01:29<00:00,  4.59it/s]
2026-04-12 03:25:38,911 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_embeddings.pt
2026-04-12 03:25:38,911 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 1280]), labels=torch.Size([26315])

[RUN ] gtex1000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:25:39,147 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41258 sequences
2026-04-12 03:25:39,147 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 645/645 [02:20<00:00,  4.60it/s]
2026-04-12 03:27:59,715 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_embeddings.pt
2026-04-12 03:27:59,717 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 1280]), labels=torch.Size([41258])
2026-04-12 03:27:59,789 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10584 sequences
2026-04-12 03:27:59,790 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 166/166 [00:36<00:00,  4.60it/s]
2026-04-12 03:28:35,904 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_10_embeddings.pt
2026-04-12 03:28:35,905 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 1280]), labels=torch.Size([10584])
2026-04-12 03:28:35,987 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9702 sequences
2026-04-12 03:28:35,988 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 152/152 [00:33<00:00,  4.60it/s]
2026-04-12 03:29:09,078 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_20_embeddings.pt
2026-04-12 03:29:09,079 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 1280]), labels=torch.Size([9702])
2026-04-12 03:29:09,155 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9152 sequences
2026-04-12 03:29:09,155 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 143/143 [00:31<00:00,  4.59it/s]
2026-04-12 03:29:40,382 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_50_embeddings.pt
2026-04-12 03:29:40,383 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 1280]), labels=torch.Size([9152])
2026-04-12 03:29:40,462 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 03:29:40,462 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 141/141 [00:30<00:00,  4.61it/s]
2026-04-12 03:30:11,095 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_100_embeddings.pt
2026-04-12 03:30:11,095 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 1280]), labels=torch.Size([8976])
2026-04-12 03:30:11,222 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 03:30:11,223 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 258/258 [00:56<00:00,  4.59it/s]
2026-04-12 03:31:07,492 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:31:07,492 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 1280]), labels=torch.Size([16500])
2026-04-12 03:31:07,613 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 03:31:07,613 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 237/237 [00:51<00:00,  4.61it/s]
2026-04-12 03:31:59,130 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:31:59,130 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 1280]), labels=torch.Size([15114])
2026-04-12 03:31:59,245 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 03:31:59,246 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 224/224 [00:48<00:00,  4.61it/s]
2026-04-12 03:32:47,932 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:32:47,933 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 1280]), labels=torch.Size([14300])
2026-04-12 03:32:48,041 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 03:32:48,041 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 219/219 [00:47<00:00,  4.61it/s]
2026-04-12 03:33:35,658 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:33:35,658 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 1280]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
[FM] params=71,719,265 | param_mem_mb=273.59 | gflops_per_sample=25.0372 (measured_profiler)
[RUN ] gencode1000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 03:33:36,323 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26315 sequences
2026-04-12 03:33:36,324 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 412/412 [00:39<00:00, 10.46it/s]
2026-04-12 03:34:15,782 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_embeddings.pt
2026-04-12 03:34:15,782 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 512]), labels=torch.Size([26315])

[RUN ] gtex1000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:34:15,993 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41258 sequences
2026-04-12 03:34:15,993 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 645/645 [01:01<00:00, 10.45it/s]
2026-04-12 03:35:17,781 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_embeddings.pt
2026-04-12 03:35:17,782 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 512]), labels=torch.Size([41258])
2026-04-12 03:35:17,866 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10584 sequences
2026-04-12 03:35:17,867 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 166/166 [00:15<00:00, 10.49it/s]
2026-04-12 03:35:33,717 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 03:35:33,717 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 512]), labels=torch.Size([10584])
2026-04-12 03:35:33,779 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9702 sequences
2026-04-12 03:35:33,779 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 152/152 [00:14<00:00, 10.44it/s]
2026-04-12 03:35:48,362 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 03:35:48,363 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 512]), labels=torch.Size([9702])
2026-04-12 03:35:48,421 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9152 sequences
2026-04-12 03:35:48,421 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 143/143 [00:13<00:00, 10.35it/s]
2026-04-12 03:36:02,258 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 03:36:02,258 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 512]), labels=torch.Size([9152])
2026-04-12 03:36:02,312 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 03:36:02,315 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 141/141 [00:13<00:00, 10.47it/s]
2026-04-12 03:36:15,797 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 03:36:15,799 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 512]), labels=torch.Size([8976])
2026-04-12 03:36:15,893 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 03:36:15,893 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 258/258 [00:24<00:00, 10.44it/s]
2026-04-12 03:36:40,632 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:36:40,633 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 512]), labels=torch.Size([16500])
2026-04-12 03:36:40,721 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 03:36:40,721 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 237/237 [00:22<00:00, 10.46it/s]
2026-04-12 03:37:03,422 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:37:03,423 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 512]), labels=torch.Size([15114])
2026-04-12 03:37:03,511 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 03:37:03,511 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 224/224 [00:21<00:00, 10.50it/s]
2026-04-12 03:37:24,872 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:37:24,873 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 512]), labels=torch.Size([14300])
2026-04-12 03:37:24,959 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 03:37:24,959 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 219/219 [00:20<00:00, 10.47it/s]
2026-04-12 03:37:45,905 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:37:45,905 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 512]), labels=torch.Size([13974])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species

2026-04-12 03:37:46,544 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26315 sequences
2026-04-12 03:37:46,544 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[FM] params=173,855,617 | param_mem_mb=663.21 | gflops_per_sample=60.3298 (measured_profiler)
[RUN ] gencode1000_test_set_1_1_raw.csv -> test_embeddings.pt

Extracting embeddings: 100%|██████████| 412/412 [00:58<00:00,  7.09it/s]
2026-04-12 03:38:44,716 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_embeddings.pt
2026-04-12 03:38:44,718 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 768]), labels=torch.Size([26315])

[RUN ] gtex1000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:38:44,974 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41258 sequences
2026-04-12 03:38:44,976 - splicing_embed_extract - INFO - Batch size: 64, FP16: True
Extracting embeddings: 100%|██████████| 645/645 [01:30<00:00,  7.10it/s]
2026-04-12 03:40:16,013 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_embeddings.pt
2026-04-12 03:40:16,014 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 768]), labels=torch.Size([41258])
2026-04-12 03:40:16,090 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10584 sequences
2026-04-12 03:40:16,092 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 166/166 [00:23<00:00,  7.11it/s]
2026-04-12 03:40:39,466 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 03:40:39,468 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 768]), labels=torch.Size([10584])
2026-04-12 03:40:39,544 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9702 sequences
2026-04-12 03:40:39,545 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 152/152 [00:21<00:00,  7.08it/s]
2026-04-12 03:41:01,041 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 03:41:01,041 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 768]), labels=torch.Size([9702])
2026-04-12 03:41:01,111 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9152 sequences
2026-04-12 03:41:01,111 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 143/143 [00:20<00:00,  7.07it/s]
2026-04-12 03:41:21,375 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 03:41:21,375 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 768]), labels=torch.Size([9152])
2026-04-12 03:41:21,451 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 03:41:21,451 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gencode1000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 141/141 [00:19<00:00,  7.11it/s]
2026-04-12 03:41:41,306 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 03:41:41,306 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 03:41:41,431 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 03:41:41,432 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 258/258 [00:36<00:00,  7.09it/s]
2026-04-12 03:42:17,884 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:42:17,884 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 03:42:17,995 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 03:42:17,995 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 237/237 [00:33<00:00,  7.11it/s]
2026-04-12 03:42:51,397 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:42:51,397 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 03:42:51,506 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 03:42:51,507 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 224/224 [00:31<00:00,  7.12it/s]
2026-04-12 03:43:23,032 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 03:43:23,032 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 03:43:23,140 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 03:43:23,141 - splicing_embed_extract - INFO - Batch size: 64, FP16: True

[RUN ] gtex1000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 219/219 [00:30<00:00,  7.11it/s]
2026-04-12 03:43:53,972 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 03:43:53,972 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

====================================================================================================
WINDOW 2000
[RAW ] gencode2000_test_set_1_1_raw.csv
[RAW ] gtex2000_test_set_1_1_raw.csv

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
[FM] params=3,277,568 | param_mem_mb=12.50 | gflops_per_sample=12.9997 (measured_profiler)
[RUN ] gencode2000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 03:44:03,403 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 03:44:03,404 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 824/824 [02:51<00:00,  4.79it/s]
2026-04-12 03:46:55,432 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_embeddings.pt
2026-04-12 03:46:55,432 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 256]), labels=torch.Size([26364])

[RUN ] gtex2000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 03:46:55,827 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 03:46:55,827 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 1284/1284 [04:27<00:00,  4.80it/s]
2026-04-12 03:51:23,377 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 03:51:23,378 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 256]), labels=torch.Size([41064])
2026-04-12 03:51:23,523 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 03:51:23,525 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 333/333 [01:09<00:00,  4.79it/s]
2026-04-12 03:52:32,986 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 03:52:32,986 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 256]), labels=torch.Size([10656])
2026-04-12 03:52:33,119 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 03:52:33,119 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 306/306 [01:03<00:00,  4.82it/s]
2026-04-12 03:53:36,622 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 03:53:36,624 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 256]), labels=torch.Size([9768])
2026-04-12 03:53:36,749 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 03:53:36,751 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 288/288 [01:00<00:00,  4.79it/s]
2026-04-12 03:54:36,842 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 03:54:36,843 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 256]), labels=torch.Size([9204])
2026-04-12 03:54:36,946 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 03:54:36,947 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 281/281 [00:58<00:00,  4.82it/s]
2026-04-12 03:55:35,285 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 03:55:35,285 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 256]), labels=torch.Size([8976])
2026-04-12 03:55:35,460 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 03:55:35,461 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 513/513 [01:46<00:00,  4.82it/s]
2026-04-12 03:57:21,899 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 03:57:21,899 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 256]), labels=torch.Size([16416])

[RUN ] gtex2000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 03:57:22,103 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 03:57:22,104 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 471/471 [01:38<00:00,  4.78it/s]
2026-04-12 03:59:00,564 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 03:59:00,566 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 256]), labels=torch.Size([15048])

[RUN ] gtex2000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 03:59:00,762 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 03:59:00,762 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 444/444 [01:32<00:00,  4.80it/s]
2026-04-12 04:00:33,294 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 04:00:33,294 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 256]), labels=torch.Size([14196])
2026-04-12 04:00:33,480 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences

[RUN ] gtex2000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 04:00:33,480 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 434/434 [01:30<00:00,  4.79it/s]
2026-04-12 04:02:04,178 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 04:02:04,178 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 256]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
[FM] params=6,550,528 | param_mem_mb=24.99 | gflops_per_sample=25.9994 (measured_profiler)
[RUN ] gencode2000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 04:02:04,717 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 04:02:04,719 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 824/824 [02:59<00:00,  4.59it/s]
2026-04-12 04:05:04,411 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_embeddings.pt
2026-04-12 04:05:04,411 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 256]), labels=torch.Size([26364])

[RUN ] gtex2000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 04:05:04,874 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 04:05:04,874 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 1284/1284 [04:39<00:00,  4.60it/s]
2026-04-12 04:09:44,025 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 04:09:44,026 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 256]), labels=torch.Size([41064])
2026-04-12 04:09:44,180 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 04:09:44,182 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 333/333 [01:11<00:00,  4.63it/s]
2026-04-12 04:10:56,045 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 04:10:56,046 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 256]), labels=torch.Size([10656])
2026-04-12 04:10:56,184 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 04:10:56,185 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 306/306 [01:05<00:00,  4.64it/s]
2026-04-12 04:12:02,135 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 04:12:02,135 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 256]), labels=torch.Size([9768])
2026-04-12 04:12:02,264 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 04:12:02,264 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 288/288 [01:02<00:00,  4.64it/s]
2026-04-12 04:13:04,378 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 04:13:04,379 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 256]), labels=torch.Size([9204])
2026-04-12 04:13:04,510 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 04:13:04,510 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 281/281 [01:00<00:00,  4.64it/s]
2026-04-12 04:14:05,101 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 04:14:05,103 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 256]), labels=torch.Size([8976])
2026-04-12 04:14:05,279 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 04:14:05,279 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 513/513 [01:50<00:00,  4.64it/s]
2026-04-12 04:15:55,803 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 04:15:55,803 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 256]), labels=torch.Size([16416])

[RUN ] gtex2000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 04:15:56,011 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 04:15:56,011 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 471/471 [01:41<00:00,  4.65it/s]
2026-04-12 04:17:37,371 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 04:17:37,372 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 256]), labels=torch.Size([15048])
2026-04-12 04:17:37,548 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences

[RUN ] gtex2000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 04:17:37,549 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 444/444 [01:35<00:00,  4.64it/s]
2026-04-12 04:19:13,200 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 04:19:13,201 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 256]), labels=torch.Size([14196])
2026-04-12 04:19:13,379 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences

[RUN ] gtex2000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 04:19:13,380 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 434/434 [01:33<00:00,  4.66it/s]
2026-04-12 04:20:46,617 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 04:20:46,618 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 256]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: DNABert_zhihan1996/DNABERT-2-117M
[FM] params=117,068,544 | param_mem_mb=446.58 | gflops_per_sample=123.5822 (measured_profiler)
[RUN ] gencode2000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 04:20:47,186 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 26364 sequences
2026-04-12 04:20:47,187 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 824/824 [02:13<00:00,  6.18it/s]
2026-04-12 04:23:00,548 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 04:23:00,548 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 768]), labels=torch.Size([26364])

[RUN ] gtex2000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 04:23:00,945 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 41064 sequences
2026-04-12 04:23:00,945 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 1284/1284 [03:26<00:00,  6.21it/s]
2026-04-12 04:26:27,914 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 04:26:27,914 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 768]), labels=torch.Size([41064])
2026-04-12 04:26:28,062 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 10656 sequences
2026-04-12 04:26:28,062 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gencode2000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 333/333 [00:54<00:00,  6.16it/s]
2026-04-12 04:27:22,124 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 04:27:22,124 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 768]), labels=torch.Size([10656])
2026-04-12 04:27:22,238 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9768 sequences
2026-04-12 04:27:22,239 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gencode2000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 306/306 [00:49<00:00,  6.21it/s]
2026-04-12 04:28:11,563 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 04:28:11,564 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 768]), labels=torch.Size([9768])
2026-04-12 04:28:11,676 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9204 sequences
2026-04-12 04:28:11,677 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gencode2000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 288/288 [00:46<00:00,  6.19it/s]
2026-04-12 04:28:58,215 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 04:28:58,216 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 768]), labels=torch.Size([9204])
2026-04-12 04:28:58,325 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 8976 sequences
2026-04-12 04:28:58,325 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gencode2000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 281/281 [00:45<00:00,  6.20it/s]
2026-04-12 04:29:43,674 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 04:29:43,674 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 04:29:43,856 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 16416 sequences
2026-04-12 04:29:43,858 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gtex2000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 513/513 [01:23<00:00,  6.18it/s]
2026-04-12 04:31:06,917 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 04:31:06,917 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 768]), labels=torch.Size([16416])
2026-04-12 04:31:07,090 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 15048 sequences
2026-04-12 04:31:07,090 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gtex2000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 471/471 [01:15<00:00,  6.20it/s]
2026-04-12 04:32:23,082 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 04:32:23,083 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 768]), labels=torch.Size([15048])
2026-04-12 04:32:23,249 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 14196 sequences
2026-04-12 04:32:23,249 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gtex2000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 444/444 [01:11<00:00,  6.19it/s]
2026-04-12 04:33:35,007 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 04:33:35,008 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 768]), labels=torch.Size([14196])
2026-04-12 04:33:35,169 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 13872 sequences
2026-04-12 04:33:35,170 - splicing_embed_extract - INFO - Batch size: 32, FP16: False

[RUN ] gtex2000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 434/434 [01:09<00:00,  6.20it/s]
2026-04-12 04:34:45,169 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 04:34:45,169 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 768]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref
[FM] params=480,438,241 | param_mem_mb=1832.73 | gflops_per_sample=331.1752 (measured_profiler)
[RUN ] gencode2000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 04:34:45,874 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 04:34:45,875 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 824/824 [03:11<00:00,  4.31it/s]
2026-04-12 04:37:57,237 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_embeddings.pt
2026-04-12 04:37:57,238 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 1280]), labels=torch.Size([26364])

[RUN ] gtex2000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 04:37:57,662 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 04:37:57,662 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 1284/1284 [04:57<00:00,  4.31it/s]
2026-04-12 04:42:55,675 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_embeddings.pt
2026-04-12 04:42:55,676 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 1280]), labels=torch.Size([41064])
2026-04-12 04:42:55,793 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 04:42:55,793 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 333/333 [01:17<00:00,  4.30it/s]
2026-04-12 04:44:13,203 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_10_embeddings.pt
2026-04-12 04:44:13,204 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 1280]), labels=torch.Size([10656])
2026-04-12 04:44:13,344 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 04:44:13,345 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 306/306 [01:10<00:00,  4.32it/s]
2026-04-12 04:45:24,309 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_20_embeddings.pt
2026-04-12 04:45:24,309 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 1280]), labels=torch.Size([9768])
2026-04-12 04:45:24,440 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 04:45:24,440 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 288/288 [01:06<00:00,  4.31it/s]
2026-04-12 04:46:31,339 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_50_embeddings.pt
2026-04-12 04:46:31,341 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 1280]), labels=torch.Size([9204])
2026-04-12 04:46:31,472 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 04:46:31,472 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 281/281 [01:05<00:00,  4.32it/s]
2026-04-12 04:47:36,592 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\test_1_1_100_embeddings.pt
2026-04-12 04:47:36,593 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 1280]), labels=torch.Size([8976])

[RUN ] gtex2000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

2026-04-12 04:47:36,791 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 04:47:36,792 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 513/513 [01:59<00:00,  4.30it/s]
2026-04-12 04:49:36,125 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_10_embeddings.pt
2026-04-12 04:49:36,126 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 1280]), labels=torch.Size([16416])

[RUN ] gtex2000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 04:49:36,332 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 04:49:36,332 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 471/471 [01:49<00:00,  4.31it/s]
2026-04-12 04:51:25,703 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_20_embeddings.pt
2026-04-12 04:51:25,703 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 1280]), labels=torch.Size([15048])

[RUN ] gtex2000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 04:51:25,899 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 04:51:25,899 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 444/444 [01:43<00:00,  4.31it/s]
2026-04-12 04:53:09,012 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_50_embeddings.pt
2026-04-12 04:53:09,013 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 1280]), labels=torch.Size([14196])

[RUN ] gtex2000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 04:53:09,205 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 04:53:09,206 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 434/434 [01:40<00:00,  4.31it/s]
2026-04-12 04:54:50,004 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-500m-human-ref\gtex_test_1_1_100_embeddings.pt
2026-04-12 04:54:50,005 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 1280]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
[FM] params=71,719,265 | param_mem_mb=273.59 | gflops_per_sample=51.7128 (measured_profiler)
[RUN ] gencode2000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 04:54:50,827 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 04:54:50,827 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 824/824 [01:28<00:00,  9.30it/s]
2026-04-12 04:56:19,508 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_embeddings.pt
2026-04-12 04:56:19,508 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 512]), labels=torch.Size([26364])

[RUN ] gtex2000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 04:56:19,904 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 04:56:19,904 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 1284/1284 [02:17<00:00,  9.31it/s]
2026-04-12 04:58:37,872 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_embeddings.pt
2026-04-12 04:58:37,872 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 512]), labels=torch.Size([41064])
2026-04-12 04:58:38,017 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 04:58:38,018 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 333/333 [00:35<00:00,  9.28it/s]
2026-04-12 04:59:13,923 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 04:59:13,923 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 512]), labels=torch.Size([10656])
2026-04-12 04:59:14,029 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 04:59:14,029 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 306/306 [00:32<00:00,  9.30it/s]
2026-04-12 04:59:46,947 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 04:59:46,947 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 512]), labels=torch.Size([9768])
2026-04-12 04:59:47,050 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 04:59:47,051 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 288/288 [00:30<00:00,  9.29it/s]
2026-04-12 05:00:18,073 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 05:00:18,074 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 512]), labels=torch.Size([9204])
2026-04-12 05:00:18,174 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 05:00:18,175 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 281/281 [00:30<00:00,  9.29it/s]
2026-04-12 05:00:48,461 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 05:00:48,462 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 512]), labels=torch.Size([8976])
2026-04-12 05:00:48,634 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 05:00:48,634 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 513/513 [00:55<00:00,  9.31it/s]
2026-04-12 05:01:43,765 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 05:01:43,766 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 512]), labels=torch.Size([16416])
2026-04-12 05:01:43,930 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 05:01:43,931 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 471/471 [00:50<00:00,  9.30it/s]
2026-04-12 05:02:34,624 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 05:02:34,624 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 512]), labels=torch.Size([15048])
2026-04-12 05:02:34,783 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 05:02:34,783 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 444/444 [00:47<00:00,  9.27it/s]
2026-04-12 05:03:22,723 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 05:03:22,723 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 512]), labels=torch.Size([14196])
2026-04-12 05:03:22,879 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 05:03:22,879 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 434/434 [00:46<00:00,  9.31it/s]
2026-04-12 05:04:09,506 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 05:04:09,507 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 512]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
[FM] params=173,855,617 | param_mem_mb=663.21 | gflops_per_sample=122.6504 (measured_profiler)
[RUN ] gencode2000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 05:04:10,211 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 05:04:10,211 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 824/824 [02:05<00:00,  6.56it/s]
2026-04-12 05:06:15,842 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_embeddings.pt
2026-04-12 05:06:15,843 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 768]), labels=torch.Size([26364])

[RUN ] gtex2000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 05:06:16,245 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 05:06:16,246 - splicing_embed_extract - INFO - Batch size: 32, FP16: True
Extracting embeddings: 100%|██████████| 1284/1284 [03:15<00:00,  6.57it/s]
2026-04-12 05:09:31,931 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_embeddings.pt
2026-04-12 05:09:31,932 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 768]), labels=torch.Size([41064])
2026-04-12 05:09:32,067 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 05:09:32,069 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 333/333 [00:50<00:00,  6.58it/s]
2026-04-12 05:10:22,718 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 05:10:22,719 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 768]), labels=torch.Size([10656])
2026-04-12 05:10:22,825 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 05:10:22,826 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 306/306 [00:46<00:00,  6.59it/s]
2026-04-12 05:11:09,281 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 05:11:09,281 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 768]), labels=torch.Size([9768])
2026-04-12 05:11:09,384 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 05:11:09,385 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 288/288 [00:43<00:00,  6.58it/s]
2026-04-12 05:11:53,158 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 05:11:53,158 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 768]), labels=torch.Size([9204])
2026-04-12 05:11:53,255 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 05:11:53,255 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gencode2000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 281/281 [00:42<00:00,  6.59it/s]
2026-04-12 05:12:35,895 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 05:12:35,896 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 05:12:36,067 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 05:12:36,067 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

Extracting embeddings: 100%|██████████| 513/513 [01:17<00:00,  6.58it/s]
2026-04-12 05:13:54,072 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 05:13:54,072 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 768]), labels=torch.Size([16416])
2026-04-12 05:13:54,240 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 05:13:54,240 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

Extracting embeddings: 100%|██████████| 471/471 [01:11<00:00,  6.59it/s]
2026-04-12 05:15:05,796 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 05:15:05,797 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 768]), labels=torch.Size([15048])
2026-04-12 05:15:05,954 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 05:15:05,954 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

Extracting embeddings: 100%|██████████| 444/444 [01:07<00:00,  6.58it/s]
2026-04-12 05:16:13,453 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 05:16:13,454 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 768]), labels=torch.Size([14196])
2026-04-12 05:16:13,612 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 05:16:13,613 - splicing_embed_extract - INFO - Batch size: 32, FP16: True

[RUN ] gtex2000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

Extracting embeddings: 100%|██████████| 434/434 [01:05<00:00,  6.59it/s]
2026-04-12 05:17:19,538 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 05:17:19,539 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 768]), labels=torch.Size([13872])

====================================================================================================
WINDOW 10000
[RAW ] gencode10000_test_set_1_1_raw.csv
[RAW ] gtex10000_test_set_1_1_raw.csv

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
[FM] params=3,277,568 | param_mem_mb=12.50 | gflops_per_sample=13.0062 (measured_profiler)
[RUN ] gencode10000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 05:18:04,315 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 05:18:04,315 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 6591/6591 [14:19<00:00,  7.67it/s]
2026-04-12 05:32:23,390 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_embeddings.pt
2026-04-12 05:32:23,391 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 256]), labels=torch.Size([26364])

[RUN ] gtex10000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 05:32:25,412 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 05:32:25,412 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 10266/10266 [22:19<00:00,  7.67it/s]
2026-04-12 05:54:44,663 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 05:54:44,664 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 256]), labels=torch.Size([41064])

[RUN ] gencode10000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

2026-04-12 05:54:45,262 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 05:54:45,263 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2664/2664 [05:47<00:00,  7.67it/s]
2026-04-12 06:00:32,508 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 06:00:32,508 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 256]), labels=torch.Size([10656])

[RUN ] gencode10000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

2026-04-12 06:00:33,029 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 06:00:33,030 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2442/2442 [05:17<00:00,  7.69it/s]
2026-04-12 06:05:50,634 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 06:05:50,634 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 256]), labels=torch.Size([9768])

[RUN ] gencode10000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

2026-04-12 06:05:51,143 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 06:05:51,144 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2301/2301 [05:00<00:00,  7.66it/s]
2026-04-12 06:10:51,369 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 06:10:51,370 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 256]), labels=torch.Size([9204])

[RUN ] gencode10000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

2026-04-12 06:10:51,871 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 06:10:51,872 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2244/2244 [04:52<00:00,  7.66it/s]
2026-04-12 06:15:44,788 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 06:15:44,789 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 256]), labels=torch.Size([8976])

[RUN ] gtex10000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

2026-04-12 06:15:45,731 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 06:15:45,731 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 4104/4104 [08:54<00:00,  7.68it/s]
2026-04-12 06:24:40,123 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 06:24:40,123 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 256]), labels=torch.Size([16416])

[RUN ] gtex10000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 06:24:41,010 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 06:24:41,010 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3762/3762 [08:09<00:00,  7.68it/s]
2026-04-12 06:32:50,821 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 06:32:50,822 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 256]), labels=torch.Size([15048])

[RUN ] gtex10000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 06:32:51,686 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 06:32:51,686 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3549/3549 [07:42<00:00,  7.68it/s]
2026-04-12 06:40:33,766 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 06:40:33,767 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 256]), labels=torch.Size([14196])

[RUN ] gtex10000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 06:40:34,651 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 06:40:34,652 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3468/3468 [07:32<00:00,  7.66it/s]
2026-04-12 06:48:07,515 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-small-32k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 06:48:07,515 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 256]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
[FM] params=6,550,528 | param_mem_mb=24.99 | gflops_per_sample=26.0124 (measured_profiler)
[RUN ] gencode10000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 06:48:09,208 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 06:48:09,208 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 6591/6591 [15:35<00:00,  7.05it/s]
2026-04-12 07:03:44,574 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_embeddings.pt
2026-04-12 07:03:44,574 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 256]), labels=torch.Size([26364])

[RUN ] gtex10000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 07:03:46,915 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 07:03:46,916 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 10266/10266 [24:19<00:00,  7.03it/s]
2026-04-12 07:28:06,743 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_embeddings.pt
2026-04-12 07:28:06,743 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 256]), labels=torch.Size([41064])

[RUN ] gencode10000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

2026-04-12 07:28:07,316 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 07:28:07,317 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2664/2664 [06:18<00:00,  7.03it/s]
2026-04-12 07:34:26,167 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_10_embeddings.pt
2026-04-12 07:34:26,167 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 256]), labels=torch.Size([10656])

[RUN ] gencode10000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

2026-04-12 07:34:26,722 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 07:34:26,723 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2442/2442 [05:46<00:00,  7.05it/s]
2026-04-12 07:40:13,326 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_20_embeddings.pt
2026-04-12 07:40:13,327 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 256]), labels=torch.Size([9768])

[RUN ] gencode10000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

2026-04-12 07:40:13,840 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 07:40:13,841 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2301/2301 [05:27<00:00,  7.03it/s]
2026-04-12 07:45:41,318 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_50_embeddings.pt
2026-04-12 07:45:41,318 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 256]), labels=torch.Size([9204])

[RUN ] gencode10000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

2026-04-12 07:45:41,818 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 07:45:41,818 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2244/2244 [05:18<00:00,  7.04it/s]
2026-04-12 07:51:00,529 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\test_1_1_100_embeddings.pt
2026-04-12 07:51:00,530 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 256]), labels=torch.Size([8976])

[RUN ] gtex10000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

2026-04-12 07:51:01,504 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 07:51:01,504 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 4104/4104 [09:43<00:00,  7.03it/s]
2026-04-12 08:00:45,132 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_10_embeddings.pt
2026-04-12 08:00:45,132 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 256]), labels=torch.Size([16416])

[RUN ] gtex10000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 08:00:45,982 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 08:00:45,983 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3762/3762 [08:53<00:00,  7.05it/s]
2026-04-12 08:09:39,874 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_20_embeddings.pt
2026-04-12 08:09:39,876 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 256]), labels=torch.Size([15048])

[RUN ] gtex10000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 08:09:40,768 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 08:09:40,769 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3549/3549 [08:24<00:00,  7.04it/s]
2026-04-12 08:18:04,979 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_50_embeddings.pt
2026-04-12 08:18:04,979 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 256]), labels=torch.Size([14196])

[RUN ] gtex10000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 08:18:05,755 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 08:18:05,757 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3468/3468 [08:12<00:00,  7.04it/s]
2026-04-12 08:26:18,318 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\HyenaDNA_LongSafari\hyenadna-medium-160k-seqlen-hf\gtex_test_1_1_100_embeddings.pt
2026-04-12 08:26:18,318 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 256]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: DNABert_zhihan1996/DNABERT-2-117M
[FM] params=117,068,544 | param_mem_mb=446.58 | gflops_per_sample=123.5822 (measured_profiler)
[RUN ] gencode10000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 08:26:20,052 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 26364 sequences
2026-04-12 08:26:20,053 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 6591/6591 [03:32<00:00, 30.97it/s]
2026-04-12 08:29:52,940 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 08:29:52,940 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 768]), labels=torch.Size([26364])

[RUN ] gtex10000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 08:29:55,258 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 41064 sequences
2026-04-12 08:29:55,258 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 10266/10266 [05:32<00:00, 30.85it/s]
2026-04-12 08:35:28,149 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 08:35:28,150 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 768]), labels=torch.Size([41064])

[RUN ] gencode10000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

2026-04-12 08:35:28,694 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 10656 sequences
2026-04-12 08:35:28,695 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2664/2664 [01:25<00:00, 31.01it/s]
2026-04-12 08:36:54,650 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 08:36:54,650 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 768]), labels=torch.Size([10656])

[RUN ] gencode10000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

2026-04-12 08:36:55,099 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9768 sequences
2026-04-12 08:36:55,100 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2442/2442 [01:18<00:00, 30.98it/s]
2026-04-12 08:38:13,952 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 08:38:13,952 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 768]), labels=torch.Size([9768])

[RUN ] gencode10000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

2026-04-12 08:38:14,382 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 9204 sequences
2026-04-12 08:38:14,384 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2301/2301 [01:14<00:00, 30.99it/s]
2026-04-12 08:39:28,666 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 08:39:28,666 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 768]), labels=torch.Size([9204])

[RUN ] gencode10000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

2026-04-12 08:39:29,085 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 8976 sequences
2026-04-12 08:39:29,085 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2244/2244 [01:12<00:00, 30.94it/s]
2026-04-12 08:40:41,637 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 08:40:41,637 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])

[RUN ] gtex10000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

2026-04-12 08:40:42,504 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 16416 sequences
2026-04-12 08:40:42,504 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 4104/4104 [02:12<00:00, 31.00it/s]
2026-04-12 08:42:54,957 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 08:42:54,959 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 768]), labels=torch.Size([16416])

[RUN ] gtex10000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 08:42:55,751 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 15048 sequences
2026-04-12 08:42:55,752 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 3762/3762 [02:01<00:00, 30.97it/s]
2026-04-12 08:44:57,275 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 08:44:57,276 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 768]), labels=torch.Size([15048])

[RUN ] gtex10000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 08:44:58,029 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 14196 sequences
2026-04-12 08:44:58,030 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 3549/3549 [01:54<00:00, 30.95it/s]
2026-04-12 08:46:52,735 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 08:46:52,735 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 768]), labels=torch.Size([14196])

[RUN ] gtex10000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 08:46:53,495 - splicing_embed_extract - INFO - Extracting embeddings using 'cls' method for 13872 sequences
2026-04-12 08:46:53,495 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 3468/3468 [01:52<00:00, 30.96it/s]
2026-04-12 08:48:45,569 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 08:48:45,569 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 768]), labels=torch.Size([13872])

[SKIP] Skipping InstaDeepAI/nucleotide-transformer-500m-human-ref for window 10000: NT v1 500M is limited to window sizes <= 5000.

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
[FM] params=71,719,265 | param_mem_mb=273.59 | gflops_per_sample=51.7128 (measured_profiler)
[RUN ] gencode10000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 08:48:47,447 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 08:48:47,447 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 6591/6591 [16:40<00:00,  6.59it/s]
2026-04-12 09:05:27,743 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_embeddings.pt
2026-04-12 09:05:27,744 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 512]), labels=torch.Size([26364])

[RUN ] gtex10000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 09:05:29,859 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 09:05:29,860 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 10266/10266 [26:11<00:00,  6.53it/s]
2026-04-12 09:31:41,928 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_embeddings.pt
2026-04-12 09:31:41,928 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 512]), labels=torch.Size([41064])

[RUN ] gencode10000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

2026-04-12 09:31:42,481 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 09:31:42,481 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2664/2664 [06:47<00:00,  6.55it/s]
2026-04-12 09:38:29,514 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 09:38:29,516 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 512]), labels=torch.Size([10656])

[RUN ] gencode10000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

2026-04-12 09:38:29,962 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 09:38:29,962 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2442/2442 [06:13<00:00,  6.55it/s]
2026-04-12 09:44:43,010 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 09:44:43,010 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 512]), labels=torch.Size([9768])

[RUN ] gencode10000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

2026-04-12 09:44:43,474 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 09:44:43,475 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2301/2301 [05:51<00:00,  6.55it/s]
2026-04-12 09:50:34,966 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 09:50:34,967 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 512]), labels=torch.Size([9204])

[RUN ] gencode10000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

2026-04-12 09:50:35,413 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 09:50:35,413 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2244/2244 [05:42<00:00,  6.55it/s]
2026-04-12 09:56:18,172 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 09:56:18,172 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 512]), labels=torch.Size([8976])

[RUN ] gtex10000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

2026-04-12 09:56:18,986 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 09:56:18,986 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 4104/4104 [10:26<00:00,  6.55it/s]
2026-04-12 10:06:45,828 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 10:06:45,836 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 512]), labels=torch.Size([16416])

[RUN ] gtex10000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 10:06:46,631 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 10:06:46,631 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3762/3762 [09:59<00:00,  6.28it/s]
2026-04-12 10:16:45,724 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 10:16:45,726 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 512]), labels=torch.Size([15048])

[RUN ] gtex10000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 10:16:46,524 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 10:16:46,524 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3549/3549 [09:36<00:00,  6.16it/s]
2026-04-12 10:26:22,657 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 10:26:22,657 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 512]), labels=torch.Size([14196])

[RUN ] gtex10000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 10:26:23,441 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 10:26:23,443 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3468/3468 [09:19<00:00,  6.20it/s]
2026-04-12 10:35:42,773 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-100m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 10:35:42,773 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 512]), labels=torch.Size([13872])

----------------------------------------------------------------------------------------------------
Loading model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
[FM] params=173,855,617 | param_mem_mb=663.21 | gflops_per_sample=122.6504 (measured_profiler)
[RUN ] gencode10000_test_set_1_1_raw.csv -> test_embeddings.pt

2026-04-12 10:35:44,845 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 10:35:44,846 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 6591/6591 [21:53<00:00,  5.02it/s]
2026-04-12 10:57:38,277 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_embeddings.pt
2026-04-12 10:57:38,278 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 768]), labels=torch.Size([26364])

[RUN ] gtex10000_test_set_1_1_raw.csv -> gtex_test_embeddings.pt

2026-04-12 10:57:40,679 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 10:57:40,679 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 10266/10266 [34:11<00:00,  5.01it/s]
2026-04-12 11:31:51,916 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_embeddings.pt
2026-04-12 11:31:51,916 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 768]), labels=torch.Size([41064])

[RUN ] gencode10000_test_set_1_1_10.csv -> test_1_1_10_embeddings.pt

2026-04-12 11:31:52,486 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 11:31:52,486 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2664/2664 [08:50<00:00,  5.02it/s]
2026-04-12 11:40:43,427 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_10_embeddings.pt
2026-04-12 11:40:43,427 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 768]), labels=torch.Size([10656])

[RUN ] gencode10000_test_set_1_1_20.csv -> test_1_1_20_embeddings.pt

2026-04-12 11:40:43,891 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 11:40:43,892 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2442/2442 [08:06<00:00,  5.02it/s]
2026-04-12 11:48:50,661 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_20_embeddings.pt
2026-04-12 11:48:50,662 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 768]), labels=torch.Size([9768])

[RUN ] gencode10000_test_set_1_1_50.csv -> test_1_1_50_embeddings.pt

2026-04-12 11:48:51,101 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 11:48:51,102 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2301/2301 [07:38<00:00,  5.02it/s]
2026-04-12 11:56:29,683 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_50_embeddings.pt
2026-04-12 11:56:29,683 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 768]), labels=torch.Size([9204])

[RUN ] gencode10000_test_set_1_1_100.csv -> test_1_1_100_embeddings.pt

2026-04-12 11:56:30,117 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 11:56:30,118 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 2244/2244 [07:28<00:00,  5.00it/s]
2026-04-12 12:03:58,819 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\test_1_1_100_embeddings.pt
2026-04-12 12:03:58,819 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])

[RUN ] gtex10000_test_set_1_1_10.csv -> gtex_test_1_1_10_embeddings.pt

2026-04-12 12:03:59,724 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 12:03:59,724 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 4104/4104 [13:00<00:00,  5.26it/s]
2026-04-12 12:16:59,989 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_10_embeddings.pt
2026-04-12 12:16:59,990 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 768]), labels=torch.Size([16416])

[RUN ] gtex10000_test_set_1_1_20.csv -> gtex_test_1_1_20_embeddings.pt

2026-04-12 12:17:00,989 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 12:17:00,990 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3762/3762 [11:54<00:00,  5.26it/s]
2026-04-12 12:28:55,812 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_20_embeddings.pt
2026-04-12 12:28:55,813 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 768]), labels=torch.Size([15048])

[RUN ] gtex10000_test_set_1_1_50.csv -> gtex_test_1_1_50_embeddings.pt

2026-04-12 12:28:56,622 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 12:28:56,622 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3549/3549 [11:14<00:00,  5.26it/s]
2026-04-12 12:40:11,068 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_50_embeddings.pt
2026-04-12 12:40:11,068 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 768]), labels=torch.Size([14196])

[RUN ] gtex10000_test_set_1_1_100.csv -> gtex_test_1_1_100_embeddings.pt

2026-04-12 12:40:11,862 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 12:40:11,863 - splicing_embed_extract - INFO - Batch size: 4, FP16: True
Extracting embeddings: 100%|██████████| 3468/3468 [10:59<00:00,  5.26it/s]
2026-04-12 12:51:11,045 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\NucleotideTransformer_InstaDeepAI\nucleotide-transformer-v2-250m-multi-species\gtex_test_1_1_100_embeddings.pt
2026-04-12 12:51:11,046 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 768]), labels=torch.Size([13872])

Done extracting embeddings (raw + imbalanced) for all MODELS_CONFIG models.
[SAVED] extract_telemetry_long_20260412_022537.csv | rows=290
[SAVED] extract_telemetry_long_20260412_022537.json | rows=290
[SAVED] extract_telemetry_model_window_20260412_022537.csv | rows=29
[SAVED] extract_telemetry_model_window_20260412_022537.json | rows=29

### Re-extract DNABERT embedding with center token (instead of CLS like before)

In [ ]:
from pathlib import Path
import runpy
import inspect

import pandas as pd
import numpy as np
import torch

# Khoi tao bien mac dinh neu kernel hien tai chua co
globals_ = globals()

if "WINDOWS" not in globals_:
    WINDOWS = [300, 600, 1000, 2000, 10000]
if "IMBALANCED_RATIOS" not in globals_:
    IMBALANCED_RATIOS = ["1_1_10", "1_1_20", "1_1_50", "1_1_100"]
if "IMBALANCED_SOURCE_DIRS" not in globals_:
    IMBALANCED_SOURCE_DIRS = {
        "gencode": Path.cwd() / "gencode",
        "gtex": Path.cwd() / "gtex",
    }
if "RAW_RATIO_TAG" not in globals_:
    RAW_RATIO_TAG = "1_1_raw"
if "TELEMETRY_DIR" not in globals_:
    TELEMETRY_DIR = Path.cwd().parent / "results" / "pipeline_telemetry"
    TELEMETRY_DIR.mkdir(parents=True, exist_ok=True)

if "psutil" not in globals_:
    try:
        import psutil
    except Exception:
        psutil = None

# Dong bo bien DEVICE/device neu chi co 1 trong 2
if "device" not in globals_ and "DEVICE" in globals_:
    try:
        device = DEVICE.type
    except Exception:
        device = "cuda" if torch.cuda.is_available() else "cpu"
if "DEVICE" not in globals_ and "device" in globals_:
    DEVICE = torch.device(device)

# Ham ho tro neu chua ton tai
if "_build_raw_default_csv" not in globals_:
    def _build_raw_default_csv(window_size: int, source_name: str):
        project_root = Path.cwd().parent
        if source_name == "gencode":
            source_file = project_root / "gencode_multi_seq_length" / f"gencode{window_size}.csv"
        else:
            source_file = project_root / "gtex_multi_seq_length" / f"gtex{window_size}.csv"

        if not source_file.exists():
            raise FileNotFoundError(f"Khong tim thay file goc: {source_file}")

        df = pd.read_csv(source_file)
        if "CHROM" not in df.columns:
            raise ValueError(f"File {source_file} thieu cot CHROM")

        raw_default_dir = Path.cwd() / "raw_default_test_set"
        raw_default_dir.mkdir(parents=True, exist_ok=True)

        raw_test_df = df[df["CHROM"].isin(["chr20", "chr21"])].copy()
        out_file = raw_default_dir / f"{source_name}{window_size}_test_set_{RAW_RATIO_TAG}.csv"
        raw_test_df.to_csv(out_file, index=False)
        return out_file

if "_param_stats" not in globals_:
    def _param_stats(model: torch.nn.Module):
        param_count = sum(p.numel() for p in model.parameters())
        param_mem_bytes = sum(p.numel() * p.element_size() for p in model.parameters())
        return int(param_count), float(param_mem_bytes / (1024 ** 2))

if "_measure_fm_gflops_per_sample" not in globals_:
    def _measure_fm_gflops_per_sample(model, tokenizer, sample_seq: str, max_length: int):
        dev = torch.device(device)
        enc = tokenizer(
            [sample_seq],
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length,
            return_attention_mask=True,
        )
        input_ids = enc["input_ids"].to(dev)
        attention_mask = enc["attention_mask"].to(dev)

        try:
            model_forward_params = set(inspect.signature(model.forward).parameters.keys())
        except Exception:
            model_forward_params = {"input_ids", "attention_mask"}

        model_inputs = {"input_ids": input_ids}
        if "attention_mask" in model_forward_params:
            model_inputs["attention_mask"] = attention_mask

        try:
            activities = [torch.profiler.ProfilerActivity.CPU]
            if dev.type == "cuda" and torch.cuda.is_available():
                activities.append(torch.profiler.ProfilerActivity.CUDA)

            with torch.inference_mode():
                with torch.profiler.profile(
                    activities=activities,
                    with_flops=True,
                    record_shapes=True,
                    acc_events=True,
                ) as prof:
                    _ = model(**model_inputs)

            total_flops = 0.0
            for evt in prof.key_averages():
                evt_flops = getattr(evt, "flops", 0)
                if evt_flops is not None:
                    total_flops += float(evt_flops)

            if total_flops > 0:
                return total_flops / 1e9, "measured_profiler"
        except Exception:
            pass

        linear_flops = {"value": 0.0}
        handles = []

        def _linear_hook(module, module_inputs, module_output):
            try:
                in_features = int(module.in_features)
                out_features = int(module.out_features)
                if isinstance(module_output, tuple):
                    out_tensor = module_output[0]
                else:
                    out_tensor = module_output
                if not torch.is_tensor(out_tensor):
                    return
                vectors = out_tensor.numel() / max(1, out_features)
                linear_flops["value"] += vectors * ((2.0 * in_features * out_features) + out_features)
            except Exception:
                return

        for mod in model.modules():
            if isinstance(mod, torch.nn.Linear):
                handles.append(mod.register_forward_hook(_linear_hook))

        try:
            with torch.inference_mode():
                _ = model(**model_inputs)
        finally:
            for h in handles:
                h.remove()

        if linear_flops["value"] > 0:
            return linear_flops["value"] / 1e9, "measured_linear_hooks"

        raise RuntimeError("Khong do duoc FM GFLOPs (profiler + linear hooks deu that bai).")

required_vars = [
    "config",
    "extractor",
    "EMBEDDINGS_DIR",
    "EMBEDDING_CONFIG",
    "MODELS_CONFIG",
    "WINDOWS",
    "IMBALANCED_RATIOS",
    "IMBALANCED_SOURCE_DIRS",
    "RAW_RATIO_TAG",
    "TELEMETRY_DIR",
    "device",
    "psutil",
    "_build_raw_default_csv",
    "_param_stats",
    "_measure_fm_gflops_per_sample",
]
missing = [v for v in required_vars if v not in globals()]
if missing:
    raise RuntimeError(
        "Thieu bien tu cac cell setup truoc do: " + ", ".join(missing)
    )

script_path = Path.cwd() / "rerun_dnabert_center_extract.py"
if not script_path.exists():
    raise FileNotFoundError(f"Khong tim thay script: {script_path}")

ctx = {
    "config": config,
    "extractor": extractor,
    "EMBEDDINGS_DIR": EMBEDDINGS_DIR,
    "EMBEDDING_CONFIG": EMBEDDING_CONFIG,
    "MODELS_CONFIG": MODELS_CONFIG,
    "WINDOWS": WINDOWS,
    "IMBALANCED_RATIOS": IMBALANCED_RATIOS,
    "IMBALANCED_SOURCE_DIRS": IMBALANCED_SOURCE_DIRS,
    "RAW_RATIO_TAG": RAW_RATIO_TAG,
    "TELEMETRY_DIR": TELEMETRY_DIR,
    "device": device,
    "psutil": psutil,
    "_build_raw_default_csv": _build_raw_default_csv,
    "_param_stats": _param_stats,
    "_measure_fm_gflops_per_sample": _measure_fm_gflops_per_sample,
}

mod = runpy.run_path(str(script_path))
if "run" not in mod:
    raise RuntimeError("Script rerun_dnabert_center_extract.py khong co ham run(context).")

mod["run"](ctx)

print("\nDone DNABERT center re-extract.")

[LOAD] DNABert_zhihan1996/DNABERT-2-117M | window=300 | pooling=center

2026-04-12 15:56:26,697 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:26,726 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 15:56:27,024 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:27,072 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 15:56:27,348 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:27,413 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-12 15:56:27,698 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-12 15:56:27,967 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-12 15:56:28,260 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:28,294 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 15:56:28,294 - models - WARNING - zhihan1996/DNABERT-2-117M requires custom code; retrying config load with trust_remote_code=True
2026-04-12 15:56:28,560 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:28,593 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 15:56:28,866 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/configuration_bert.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:28,897 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/configuration_bert.py "HTTP/1.1 200 OK"
2026-04-12 15:56:29,162 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-12 15:56:29,165 - huggingface_hub.utils._http - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-04-12 15:56:29,196 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/config.json "HTTP/1.1 200 OK"
2026-04-12 15:56:29,507 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:29,546 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 15:56:29,879 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-04-12 15:56:29,891 - models - WARNING - Retrying zhihan1996/DNABERT-2-117M with low_cpu_mem_usage=False and ignore_mismatched_sizes=True to resolve meta-device tensors
2026-04-12 15:56:30,145 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M "HTTP/1.1 200 OK"
2026-04-12 15:56:30,229 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:30,258 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 15:56:30,436 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/main "HTTP/1.1 200 OK"
2026-04-12 15:56:30,532 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-04-12 15:56:30,542 - models - WARNING - Falling back to DNABERT MLM loader for zhihan1996/DNABERT-2-117M and using its backbone encoder
2026-04-12 15:56:30,729 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 15:56:30,799 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M "HTTP/1.1 200 OK"
2026-04-12 15:56:30,896 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:30,926 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 15:56:31,014 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/refs%2Fpr%2F40 "HTTP/1.1 200 OK"
2026-04-12 15:56:31,096 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/main "HTTP/1.1 200 OK"
2026-04-12 15:56:31,210 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-04-12 15:56:31,222 - models - WARNING - Final fallback: manual state_dict load for zhihan1996/DNABERT-2-117M to bypass meta tensors
2026-04-12 15:56:31,284 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-04-12 15:56:31,385 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 15:56:31,477 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M "HTTP/1.1 200 OK"
2026-04-12 15:56:31,544 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/bert_layers.py "HTTP/1.1 307 Temporary Redirect"
2026-04-12 15:56:31,560 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors "HTTP/1.1 302 Found"
2026-04-12 15:56:31,573 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/zhihan1996/DNABERT-2-117M/7bce263b15377fc15361f52cfab88f8b586abda0/bert_layers.py "HTTP/1.1 200 OK"
2026-04-12 15:56:31,683 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/refs%2Fpr%2F40 "HTTP/1.1 200 OK"
2026-04-12 15:56:31,803 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/main "HTTP/1.1 200 OK"
2026-04-12 15:56:31,944 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-04-12 15:56:32,095 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/discussions?p=0 "HTTP/1.1 200 OK"
2026-04-12 15:56:32,221 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors "HTTP/1.1 302 Found"
2026-04-12 15:56:32,221 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
2026-04-12 15:56:32,309 - models - WARNING - Manual load missing keys: 138
2026-04-12 15:56:32,309 - models - WARNING - Manual load unexpected keys: 142
2026-04-12 15:56:32,309 - models - INFO - Patched DNABERT remote flash attention in 2 module(s); using PyTorch attention path
2026-04-12 15:56:32,386 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/zhihan1996/DNABERT-2-117M/commits/refs%2Fpr%2F40 "HTTP/1.1 200 OK"
2026-04-12 15:56:32,416 - models - INFO - Successfully loaded DNABert model: zhihan1996/DNABERT-2-117M
2026-04-12 15:56:32,774 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-04-12 15:56:32,909 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26450 sequences
2026-04-12 15:56:32,909 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings:   1%|          | 1/104 [00:00<00:20,  5.10it/s]2026-04-12 15:56:33,115 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/zhihan1996/DNABERT-2-117M/resolve/refs%2Fpr%2F40/model.safetensors "HTTP/1.1 302 Found"
Extracting embeddings: 100%|██████████| 104/104 [00:18<00:00,  5.53it/s]
2026-04-12 15:56:51,793 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 15:56:51,795 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26450, 768]), labels=torch.Size([26450])
2026-04-12 15:56:51,906 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41262 sequences
2026-04-12 15:56:51,906 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 162/162 [00:29<00:00,  5.56it/s]
2026-04-12 15:57:21,158 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 15:57:21,159 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41262, 768]), labels=torch.Size([41262])
2026-04-12 15:57:21,205 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10752 sequences
2026-04-12 15:57:21,205 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 42/42 [00:07<00:00,  5.44it/s]
2026-04-12 15:57:28,960 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 15:57:28,960 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10752, 768]), labels=torch.Size([10752])
2026-04-12 15:57:28,999 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9856 sequences
2026-04-12 15:57:29,000 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 39/39 [00:07<00:00,  5.52it/s]
2026-04-12 15:57:36,105 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 15:57:36,105 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9856, 768]), labels=torch.Size([9856])
2026-04-12 15:57:36,143 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9308 sequences
2026-04-12 15:57:36,143 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 37/37 [00:06<00:00,  5.56it/s]
2026-04-12 15:57:42,833 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 15:57:42,833 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9308, 768]), labels=torch.Size([9308])
2026-04-12 15:57:42,870 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 15:57:42,871 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 36/36 [00:06<00:00,  5.48it/s]
2026-04-12 15:57:49,474 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 15:57:49,474 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 768]), labels=torch.Size([9078])
2026-04-12 15:57:49,526 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 15:57:49,526 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 65/65 [00:11<00:00,  5.51it/s]
2026-04-12 15:58:01,372 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 15:58:01,373 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 15:58:01,418 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 15:58:01,419 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 60/60 [00:10<00:00,  5.55it/s]
2026-04-12 15:58:12,292 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 15:58:12,292 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 15:58:12,339 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 15:58:12,342 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 56/56 [00:10<00:00,  5.47it/s]
2026-04-12 15:58:22,626 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 15:58:22,631 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 15:58:22,680 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 15:58:22,680 - splicing_embed_extract - INFO - Batch size: 256, FP16: False
Extracting embeddings: 100%|██████████| 55/55 [00:09<00:00,  5.50it/s]
2026-04-12 15:58:32,722 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\300\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 15:58:32,722 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

[LOAD] DNABert_zhihan1996/DNABERT-2-117M | window=600 | pooling=center

2026-04-12 15:58:36,016 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26401 sequences
2026-04-12 15:58:36,019 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 207/207 [00:38<00:00,  5.34it/s]
2026-04-12 15:59:14,849 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 15:59:14,849 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26401, 768]), labels=torch.Size([26401])
2026-04-12 15:59:15,032 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41261 sequences
2026-04-12 15:59:15,032 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 323/323 [00:55<00:00,  5.82it/s]
2026-04-12 16:00:10,689 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 16:00:10,691 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41261, 768]), labels=torch.Size([41261])
2026-04-12 16:00:10,748 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10692 sequences
2026-04-12 16:00:10,748 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 84/84 [00:15<00:00,  5.58it/s]
2026-04-12 16:00:25,840 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 16:00:25,840 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10692, 768]), labels=torch.Size([10692])
2026-04-12 16:00:25,889 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9790 sequences
2026-04-12 16:00:25,889 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 77/77 [00:14<00:00,  5.41it/s]
2026-04-12 16:00:40,147 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 16:00:40,150 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9790, 768]), labels=torch.Size([9790])
2026-04-12 16:00:40,202 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9256 sequences
2026-04-12 16:00:40,202 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 73/73 [00:13<00:00,  5.45it/s]
2026-04-12 16:00:53,619 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 16:00:53,619 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9256, 768]), labels=torch.Size([9256])
2026-04-12 16:00:53,676 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9078 sequences
2026-04-12 16:00:53,676 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 71/71 [00:13<00:00,  5.43it/s]
2026-04-12 16:01:06,773 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 16:01:06,773 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9078, 768]), labels=torch.Size([9078])
2026-04-12 16:01:06,851 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 16:01:06,851 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 129/129 [00:23<00:00,  5.59it/s]
2026-04-12 16:01:29,991 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 16:01:29,991 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 16:01:30,058 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 16:01:30,058 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 119/119 [00:21<00:00,  5.61it/s]
2026-04-12 16:01:51,324 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 16:01:51,324 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 16:01:51,398 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 16:01:51,398 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 112/112 [00:19<00:00,  5.61it/s]
2026-04-12 16:02:11,402 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 16:02:11,402 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 16:02:11,467 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 16:02:11,468 - splicing_embed_extract - INFO - Batch size: 128, FP16: False
Extracting embeddings: 100%|██████████| 110/110 [00:19<00:00,  5.64it/s]
2026-04-12 16:02:31,031 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\600\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 16:02:31,031 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

[LOAD] DNABert_zhihan1996/DNABERT-2-117M | window=1000 | pooling=center

2026-04-12 16:02:36,059 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26315 sequences
2026-04-12 16:02:36,064 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 412/412 [01:03<00:00,  6.45it/s]
2026-04-12 16:03:39,997 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 16:03:39,998 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26315, 768]), labels=torch.Size([26315])
2026-04-12 16:03:40,231 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41258 sequences
2026-04-12 16:03:40,231 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 645/645 [01:39<00:00,  6.46it/s]
2026-04-12 16:05:20,271 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 16:05:20,283 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41258, 768]), labels=torch.Size([41258])
2026-04-12 16:05:20,366 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10584 sequences
2026-04-12 16:05:20,367 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 166/166 [00:25<00:00,  6.46it/s]
2026-04-12 16:05:46,092 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 16:05:46,093 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10584, 768]), labels=torch.Size([10584])
2026-04-12 16:05:46,169 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9702 sequences
2026-04-12 16:05:46,170 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 152/152 [00:23<00:00,  6.46it/s]
2026-04-12 16:06:09,749 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 16:06:09,750 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9702, 768]), labels=torch.Size([9702])
2026-04-12 16:06:09,827 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9152 sequences
2026-04-12 16:06:09,828 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 143/143 [00:22<00:00,  6.44it/s]
2026-04-12 16:06:32,062 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 16:06:32,063 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9152, 768]), labels=torch.Size([9152])
2026-04-12 16:06:32,130 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 16:06:32,131 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 141/141 [00:21<00:00,  6.48it/s]
2026-04-12 16:06:53,925 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 16:06:53,925 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 16:06:54,030 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16500 sequences
2026-04-12 16:06:54,030 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 258/258 [00:39<00:00,  6.47it/s]
2026-04-12 16:07:33,970 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 16:07:33,970 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16500, 768]), labels=torch.Size([16500])
2026-04-12 16:07:34,089 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15114 sequences
2026-04-12 16:07:34,091 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 237/237 [00:36<00:00,  6.50it/s]
2026-04-12 16:08:10,611 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 16:08:10,612 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15114, 768]), labels=torch.Size([15114])
2026-04-12 16:08:10,721 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14300 sequences
2026-04-12 16:08:10,721 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 224/224 [00:34<00:00,  6.40it/s]
2026-04-12 16:08:45,751 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 16:08:45,752 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14300, 768]), labels=torch.Size([14300])
2026-04-12 16:08:45,852 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13974 sequences
2026-04-12 16:08:45,853 - splicing_embed_extract - INFO - Batch size: 64, FP16: False
Extracting embeddings: 100%|██████████| 219/219 [00:33<00:00,  6.45it/s]
2026-04-12 16:09:19,833 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\1000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 16:09:19,833 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13974, 768]), labels=torch.Size([13974])

[LOAD] DNABert_zhihan1996/DNABERT-2-117M | window=2000 | pooling=center

2026-04-12 16:09:29,099 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 16:09:29,100 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 824/824 [02:18<00:00,  5.97it/s]
2026-04-12 16:11:47,291 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 16:11:47,293 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 768]), labels=torch.Size([26364])
2026-04-12 16:11:47,714 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 16:11:47,714 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 1284/1284 [03:30<00:00,  6.11it/s]
2026-04-12 16:15:18,150 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 16:15:18,150 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 768]), labels=torch.Size([41064])
2026-04-12 16:15:18,298 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 16:15:18,299 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 333/333 [00:55<00:00,  5.98it/s]
2026-04-12 16:16:14,014 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 16:16:14,014 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 768]), labels=torch.Size([10656])
2026-04-12 16:16:14,127 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 16:16:14,127 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 306/306 [00:50<00:00,  6.12it/s]
2026-04-12 16:17:04,167 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 16:17:04,167 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 768]), labels=torch.Size([9768])
2026-04-12 16:17:04,279 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 16:17:04,281 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 288/288 [00:47<00:00,  6.00it/s]
2026-04-12 16:17:52,311 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 16:17:52,311 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 768]), labels=torch.Size([9204])
2026-04-12 16:17:52,420 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 16:17:52,421 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 281/281 [00:48<00:00,  5.74it/s]
2026-04-12 16:18:41,372 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 16:18:41,372 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 16:18:41,547 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 16:18:41,547 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 513/513 [01:29<00:00,  5.74it/s]
2026-04-12 16:20:11,041 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 16:20:11,041 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 768]), labels=torch.Size([16416])
2026-04-12 16:20:11,207 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 16:20:11,207 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 471/471 [01:20<00:00,  5.84it/s]
2026-04-12 16:21:31,919 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 16:21:31,920 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 768]), labels=torch.Size([15048])
2026-04-12 16:21:32,084 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 16:21:32,084 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 444/444 [01:16<00:00,  5.83it/s]
2026-04-12 16:22:48,245 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 16:22:48,245 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 768]), labels=torch.Size([14196])
2026-04-12 16:22:48,408 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 16:22:48,408 - splicing_embed_extract - INFO - Batch size: 32, FP16: False
Extracting embeddings: 100%|██████████| 434/434 [01:14<00:00,  5.84it/s]
2026-04-12 16:24:02,759 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\2000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 16:24:02,759 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 768]), labels=torch.Size([13872])

[LOAD] DNABert_zhihan1996/DNABERT-2-117M | window=10000 | pooling=center

2026-04-12 16:24:46,806 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 26364 sequences
2026-04-12 16:24:46,806 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 6591/6591 [03:33<00:00, 30.81it/s]
2026-04-12 16:28:20,822 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_embeddings.pt
2026-04-12 16:28:20,823 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([26364, 768]), labels=torch.Size([26364])
2026-04-12 16:28:22,759 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 41064 sequences
2026-04-12 16:28:22,760 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 10266/10266 [05:31<00:00, 30.99it/s]
2026-04-12 16:33:54,126 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_embeddings.pt
2026-04-12 16:33:54,126 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([41064, 768]), labels=torch.Size([41064])
2026-04-12 16:33:54,647 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 10656 sequences
2026-04-12 16:33:54,647 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2664/2664 [01:27<00:00, 30.57it/s]
2026-04-12 16:35:21,826 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_10_embeddings.pt
2026-04-12 16:35:21,827 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([10656, 768]), labels=torch.Size([10656])
2026-04-12 16:35:22,295 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9768 sequences
2026-04-12 16:35:22,296 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2442/2442 [01:19<00:00, 30.87it/s]
2026-04-12 16:36:41,442 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_20_embeddings.pt
2026-04-12 16:36:41,442 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9768, 768]), labels=torch.Size([9768])
2026-04-12 16:36:41,893 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 9204 sequences
2026-04-12 16:36:41,893 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2301/2301 [01:12<00:00, 31.82it/s]
2026-04-12 16:37:54,251 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_50_embeddings.pt
2026-04-12 16:37:54,252 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([9204, 768]), labels=torch.Size([9204])
2026-04-12 16:37:54,674 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 8976 sequences
2026-04-12 16:37:54,675 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 2244/2244 [01:12<00:00, 31.16it/s]
2026-04-12 16:39:06,709 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\test_1_1_100_embeddings.pt
2026-04-12 16:39:06,709 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([8976, 768]), labels=torch.Size([8976])
2026-04-12 16:39:07,518 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 16416 sequences
2026-04-12 16:39:07,519 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 4104/4104 [02:09<00:00, 31.66it/s]
2026-04-12 16:41:17,209 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_10_embeddings.pt
2026-04-12 16:41:17,209 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([16416, 768]), labels=torch.Size([16416])
2026-04-12 16:41:17,949 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 15048 sequences
2026-04-12 16:41:17,958 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 3762/3762 [01:58<00:00, 31.68it/s]
2026-04-12 16:43:16,743 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_20_embeddings.pt
2026-04-12 16:43:16,743 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([15048, 768]), labels=torch.Size([15048])
2026-04-12 16:43:17,479 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 14196 sequences
2026-04-12 16:43:17,479 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 3549/3549 [01:53<00:00, 31.16it/s]
2026-04-12 16:45:11,404 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_50_embeddings.pt
2026-04-12 16:45:11,404 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([14196, 768]), labels=torch.Size([14196])
2026-04-12 16:45:12,180 - splicing_embed_extract - INFO - Extracting embeddings using 'center' method for 13872 sequences
2026-04-12 16:45:12,184 - splicing_embed_extract - INFO - Batch size: 4, FP16: False
Extracting embeddings: 100%|██████████| 3468/3468 [01:53<00:00, 30.54it/s]
2026-04-12 16:47:05,789 - splicing_embed_extract - INFO - ✓ Saved embeddings: d:\Splice_FMs_seq_lengths\data\embeddings\10000\DNABert_zhihan1996\DNABERT-2-117M\gtex_test_1_1_100_embeddings.pt
2026-04-12 16:47:05,789 - splicing_embed_extract - INFO -   Shape: embeddings=torch.Size([13872, 768]), labels=torch.Size([13872])

[DONE] DNABERT center re-extract + full telemetry merge
[CHECK] pooling_method counts in DNABERT rows:
pooling_method
center    50
Name: count, dtype: int64
[SAVED] extract_telemetry_long_20260412_164705.csv | rows=290

Done DNABERT center re-extract.

In [4]:
from pathlib import Path

check_windows = [300, 600, 1000, 2000, 10000]
check_ratios = ['1_1_10', '1_1_20', '1_1_50', '1_1_100']
base_embed = Path.cwd().parent / 'data' / 'embeddings'

for ws in check_windows:
    print('\n' + '=' * 100)
    print(f'Check window {ws}')

    for model_name, model_cfg in MODELS_CONFIG.items():
        for model_id in model_cfg.get('model_ids', []):
            if config.get_model_window_skip_reason(model_name, model_id, ws) is not None:
                continue

            model_dir = base_embed / str(ws) / f'{model_name}_{model_id}'
            print(f'  Model: {model_name}_{model_id}')
            print(f'  Dir exists: {model_dir.exists()}')

            for rt in check_ratios:
                f1 = model_dir / f'test_{rt}_embeddings.pt'
                f2 = model_dir / f'gtex_test_{rt}_embeddings.pt'
                print(f'    GENCODE {rt}: {f1.exists()}')
                print(f'    GTEx    {rt}: {f2.exists()}')

====================================================================================================
Check window 300
  Model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: DNABert_zhihan1996/DNABERT-2-117M
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True

====================================================================================================
Check window 600
  Model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: DNABert_zhihan1996/DNABERT-2-117M
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True

====================================================================================================
Check window 1000
  Model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: DNABert_zhihan1996/DNABERT-2-117M
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True

====================================================================================================
Check window 2000
  Model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: DNABert_zhihan1996/DNABERT-2-117M
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True

====================================================================================================
Check window 10000
  Model: HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: DNABert_zhihan1996/DNABERT-2-117M
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True
  Model: NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species
  Dir exists: True
    GENCODE 1_1_10: True
    GTEx    1_1_10: True
    GENCODE 1_1_20: True
    GTEx    1_1_20: True
    GENCODE 1_1_50: True
    GTEx    1_1_50: True
    GENCODE 1_1_100: True
    GTEx    1_1_100: True

### Inference

In [1]:
import json
import os
import re
import sys
import time
import importlib
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import torch

try:
    import psutil
except Exception:
    psutil = None

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root / 'src'))

import config
importlib.reload(config)
from config import EMBEDDINGS_DIR, SPLICING_RESULTS_DIR
from splicing_classifier import SpliceSiteClassifier
from splicing_metrics import MetricsComputer

EXCLUDE_EXPERIMENTS = {'DNABERT-2-117M_CLS_w300_quick'}
RESULTS_ROOT = Path(SPLICING_RESULTS_DIR)
SUMMARY_DIR = RESULTS_ROOT / 'summaries'
SUMMARY_DIR.mkdir(parents=True, exist_ok=True)
TELEMETRY_DIR = project_root / 'results' / 'pipeline_telemetry'
TELEMETRY_DIR.mkdir(parents=True, exist_ok=True)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
RAW_RATIO_TAG = '1_1_raw'
RATIOS = [RAW_RATIO_TAG, '1_1_10', '1_1_20', '1_1_50', '1_1_100']
INFER_BATCH_SIZE = 1024
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

print(f'Results root: {RESULTS_ROOT}')
print(f'Embeddings root: {EMBEDDINGS_DIR}')
print(f'Telemetry root: {TELEMETRY_DIR}')
print(f'Device: {DEVICE}')
print(f'psutil available: {psutil is not None}')

def _to_serializable(obj):
    if isinstance(obj, dict):
        return {k: _to_serializable(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_to_serializable(v) for v in obj]
    if isinstance(obj, (np.integer, np.floating)):
        return obj.item()
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    return obj

def _normalize_path_str(p):
    try:
        s = str(Path(p))
    except Exception:
        s = str(p)
    s = s.replace('/', '\\')
    return os.path.normcase(os.path.normpath(s))

def _resolve_best_checkpoint(exp_dir: Path, cv_results: dict):
    best_fold_info = cv_results.get('best_fold', {}) or {}
    checkpoint_path = best_fold_info.get('checkpoint_path', None)
    checkpoint_name = best_fold_info.get('checkpoint', None)
    fold_number = best_fold_info.get('fold_number', None)

    if checkpoint_name is None:
        fold_entries = cv_results.get('per_fold_results', {}) or {}
        if not fold_entries:
            return None, None, None

        best_key = None
        best_mcc = -1e9
        for fold_key, fold_val in fold_entries.items():
            mcc = fold_val.get('best_mcc', -1e9)
            if mcc > best_mcc:
                best_mcc = mcc
                best_key = fold_key

        if best_key is None:
            return None, None, None

        checkpoint_name = fold_entries[best_key].get('best_checkpoint', None)
        if checkpoint_name is None:
            try:
                fold_idx = int(best_key.replace('fold_', ''))
                checkpoint_name = f'best_fold{fold_idx + 1}.pt'
            except Exception:
                checkpoint_name = None

        try:
            fold_number = int(best_key.replace('fold_', '')) + 1
        except Exception:
            fold_number = None

    checkpoint_path_obj = None
    if checkpoint_path is not None:
        checkpoint_path_obj = Path(checkpoint_path)
        if not checkpoint_path_obj.exists():
            checkpoint_path_obj = None

    if checkpoint_path_obj is None and checkpoint_name is not None:
        checkpoint_path_obj = exp_dir / 'checkpoints' / checkpoint_name

    if checkpoint_path_obj is None or not checkpoint_path_obj.exists():
        return None, checkpoint_name, fold_number

    return checkpoint_path_obj, checkpoint_name, fold_number

def _parse_experiment(exp_dir: Path):
    family_name = exp_dir.parent.name
    exp_name = exp_dir.name
    m = re.search(r'_w(\d+)', exp_name)
    if m is None:
        return None
    window_size = int(m.group(1))
    model_variant = exp_name.split(f'_w{window_size}', 1)[0]
    embed_dir = EMBEDDINGS_DIR / str(window_size) / family_name / model_variant
    return {
        'family_name': family_name,
        'exp_name': exp_name,
        'window_size': window_size,
        'model_variant': model_variant,
        'embed_dir': embed_dir,
    }

def _list_embedding_targets(embed_dir: Path):
    targets = [
        ('gencode', RAW_RATIO_TAG, embed_dir / 'test_embeddings.pt'),
        ('gtex', RAW_RATIO_TAG, embed_dir / 'gtex_test_embeddings.pt'),
    ]
    for ratio in RATIOS:
        if ratio == RAW_RATIO_TAG:
            continue
        targets.append(('gencode', ratio, embed_dir / f'test_{ratio}_embeddings.pt'))
        targets.append(('gtex', ratio, embed_dir / f'gtex_test_{ratio}_embeddings.pt'))
    return [(dataset, ratio, fp) for dataset, ratio, fp in targets if fp.exists()]

def _classifier_gflops_per_sample(model: torch.nn.Module):
    total_flops = 0.0
    for layer in model.modules():
        if isinstance(layer, torch.nn.Linear):
            in_dim = int(layer.in_features)
            out_dim = int(layer.out_features)
            total_flops += (2.0 * in_dim * out_dim) + out_dim
    return total_flops / 1e9

def _model_param_stats(model: torch.nn.Module):
    param_count = sum(p.numel() for p in model.parameters())
    param_mem_bytes = sum(p.numel() * p.element_size() for p in model.parameters())
    return int(param_count), float(param_mem_bytes / (1024 ** 2))

def _run_inference_on_embedding_file(checkpoint_payload, embedding_file, batch_size=1024):
    data = torch.load(embedding_file, map_location='cpu')
    embeddings = data['embeddings']
    labels = data['labels']

    if not isinstance(embeddings, torch.Tensor):
        embeddings = torch.tensor(embeddings, dtype=torch.float32)
    else:
        embeddings = embeddings.float()

    if not isinstance(labels, torch.Tensor):
        labels = torch.tensor(labels, dtype=torch.long)
    else:
        labels = labels.long()

    cpu_before_mb = np.nan
    cpu_after_mb = np.nan
    if psutil is not None:
        proc = psutil.Process(os.getpid())
        cpu_before_mb = proc.memory_info().rss / (1024 ** 2)

    if DEVICE.type == 'cuda':
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    model_state = checkpoint_payload.get('model_state_dict', checkpoint_payload)
    embedding_dim = int(checkpoint_payload.get('embedding_dim', embeddings.shape[1]))
    num_classes = int(checkpoint_payload.get('num_classes', 3))

    model = SpliceSiteClassifier(
        embedding_dim=embedding_dim,
        num_classes=num_classes,
        hidden_dims=[512, 256],
        dropout_rate=0.3,
    ).to(DEVICE)
    model.load_state_dict(model_state)
    model.eval()

    param_count, param_mem_mb = _model_param_stats(model)
    gflops_per_sample = _classifier_gflops_per_sample(model)

    all_preds = []
    all_probs = []
    start_time = time.perf_counter()
    with torch.no_grad():
        for start_idx in range(0, len(embeddings), batch_size):
            end_idx = min(start_idx + batch_size, len(embeddings))
            batch_x = embeddings[start_idx:end_idx].to(DEVICE, non_blocking=(DEVICE.type == 'cuda'))
            logits = model(batch_x)
            probs = torch.softmax(logits, dim=1)
            preds = torch.argmax(logits, dim=1)
            all_preds.append(preds.cpu())
            all_probs.append(probs.cpu())
    infer_seconds = float(time.perf_counter() - start_time)

    gpu_peak_mb = np.nan
    if DEVICE.type == 'cuda':
        gpu_peak_mb = float(torch.cuda.max_memory_allocated() / (1024 ** 2))

    if psutil is not None:
        proc = psutil.Process(os.getpid())
        cpu_after_mb = proc.memory_info().rss / (1024 ** 2)

    y_true = labels.cpu().numpy()
    y_pred = torch.cat(all_preds, dim=0).numpy()
    y_prob = torch.cat(all_probs, dim=0).numpy()
    metrics, cm = MetricsComputer.compute_metrics(y_true, y_pred, y_prob)

    del model
    if DEVICE.type == 'cuda':
        torch.cuda.empty_cache()

    return {
        'num_samples': int(len(y_true)),
        'running_time_seconds': infer_seconds,
        'cpu_ram_delta_mb': float(cpu_after_mb - cpu_before_mb) if psutil is not None else np.nan,
        'gpu_peak_memory_mb': float(gpu_peak_mb),
        'param_count': param_count,
        'model_param_memory_mb': param_mem_mb,
        'gflops_per_sample': float(gflops_per_sample),
        'gflops_total': float(gflops_per_sample * len(y_true)),
        'metrics': {k: float(v) if isinstance(v, (int, float, np.number)) else v for k, v in metrics.items()},
        'confusion_matrix': cm.tolist(),
    }

result_rows = []
legacy_inference_results = {}
result_files = sorted(RESULTS_ROOT.glob('*/*/results.json'))
print(f'Found experiments with results.json: {len(result_files)}')

for rs_file in result_files:
    exp_dir = rs_file.parent
    parsed = _parse_experiment(exp_dir)
    if parsed is None:
        continue

    if parsed['exp_name'] in EXCLUDE_EXPERIMENTS:
        print(f"[SKIP-EXCLUDED] {parsed['exp_name']}")
        continue

    with open(rs_file, 'r', encoding='utf-8') as f:
        cv_results = json.load(f)

    checkpoint_path, checkpoint_name, fold_number = _resolve_best_checkpoint(exp_dir, cv_results)
    if checkpoint_path is None:
        print(f"[SKIP-NOCKPT] {exp_dir}")
        continue

    targets = _list_embedding_targets(parsed['embed_dir'])
    if not targets:
        print(f"[SKIP-NO-EMB] {parsed['embed_dir']}")
        continue

    checkpoint_payload = torch.load(checkpoint_path, map_location='cpu')
    model_infer_total = 0.0

    print(f"[RUN] {parsed['family_name']}/{parsed['exp_name']} | targets={len(targets)}")

    for dataset_name, ratio_name, emb_file in targets:
        infer_out = _run_inference_on_embedding_file(
            checkpoint_payload=checkpoint_payload,
            embedding_file=emb_file,
            batch_size=INFER_BATCH_SIZE,
        )
        model_infer_total += infer_out['running_time_seconds']
        row = {
            'timestamp': timestamp,
            'stage': 'mlp_inference',
            'family': parsed['family_name'],
            'model_id': parsed['model_variant'],
            'model_variant': parsed['model_variant'],
            'experiment': parsed['exp_name'],
            'window_size': parsed['window_size'],
            'dataset': dataset_name,
            'ratio': ratio_name,
            'best_fold_number': fold_number,
            'checkpoint': checkpoint_name,
            'best_checkpoint': str(checkpoint_path),
            'embedding_file': str(emb_file),
            'running_time_seconds': infer_out['running_time_seconds'],
            'model_inference_seconds_total': np.nan,
            'n_samples': infer_out['num_samples'],
            'param_count': infer_out['param_count'],
            'model_param_memory_mb': infer_out['model_param_memory_mb'],
            'gpu_peak_memory_mb': infer_out['gpu_peak_memory_mb'],
            'cpu_ram_delta_mb': infer_out['cpu_ram_delta_mb'],
            'gflops_per_sample': infer_out['gflops_per_sample'],
            'gflops_total': infer_out['gflops_total'],
            'confusion_matrix': json.dumps(infer_out['confusion_matrix']),
            **infer_out['metrics'],
        }
        result_rows.append(row)

    for row in result_rows[::-1]:
        if row['experiment'] == parsed['exp_name']:
            row['model_inference_seconds_total'] = float(model_infer_total)
        else:
            break

    default_gencode = [r for r in result_rows if r['experiment'] == parsed['exp_name'] and r['ratio'] == RAW_RATIO_TAG and r['dataset'] == 'gencode']
    default_gtex = [r for r in result_rows if r['experiment'] == parsed['exp_name'] and r['ratio'] == RAW_RATIO_TAG and r['dataset'] == 'gtex']
    if default_gencode and default_gtex:
        dg = default_gencode[-1]
        dt = default_gtex[-1]
        metric_keys = [k for k in dg.keys() if k.startswith('accuracy') or k.startswith('f1') or k.startswith('mcc') or k.startswith('balanced') or k.startswith('roc_auc') or k.startswith('pr_auc')]
        legacy_inference_results[parsed['exp_name']] = {
            'window_size': parsed['window_size'],
            'model_name': parsed['family_name'].split('_')[0],
            'model_id': parsed['model_variant'],
            'best_fold_number': fold_number,
            'checkpoint': checkpoint_name,
            'checkpoint_path': str(checkpoint_path),
            'model_inference_seconds_total': float(model_infer_total),
            'gencode_test': {
                'num_samples': int(dg['n_samples']),
                'metrics': {k: dg[k] for k in metric_keys if k in dg},
                'confusion_matrix': json.loads(dg['confusion_matrix']),
                'running_time_seconds': float(dg['running_time_seconds']),
            },
            'gtex_test': {
                'num_samples': int(dt['n_samples']),
                'metrics': {k: dt[k] for k in metric_keys if k in dt},
                'confusion_matrix': json.loads(dt['confusion_matrix']),
                'running_time_seconds': float(dt['running_time_seconds']),
            },
        }

if not result_rows:
    raise RuntimeError('Khong co ket qua inference nao duoc tao. Kiem tra embeddings/results folders.')

mlp_df = pd.DataFrame(result_rows)

mlp_long_csv = TELEMETRY_DIR / f'mlp_inference_telemetry_long_{timestamp}.csv'
mlp_long_json = TELEMETRY_DIR / f'mlp_inference_telemetry_long_{timestamp}.json'
mlp_df.to_csv(mlp_long_csv, index=False)
mlp_df.to_json(mlp_long_json, orient='records', indent=2)

extract_long_candidates = sorted(TELEMETRY_DIR.glob('extract_telemetry_long_*.csv'))
if not extract_long_candidates:
    raise RuntimeError('Khong tim thay extract telemetry. Hay chay cell Extract embedding truoc.')
extract_long_path = extract_long_candidates[-1]
extract_df = pd.read_csv(extract_long_path)

# Robust join by exact embedding file path (normalized), because family/model_id naming differs
fm_cols = [
    'running_time_seconds', 'param_count', 'model_param_memory_mb',
    'gpu_peak_memory_mb', 'cpu_ram_delta_mb', 'gflops_per_sample', 'gflops_total', 'gflops_method'
    ]
fm_df = extract_df[['output_embedding'] + fm_cols].copy()
fm_df['embedding_key'] = fm_df['output_embedding'].map(_normalize_path_str)
fm_df = fm_df.rename(columns={
    'running_time_seconds': 'fm_running_time_seconds',
    'param_count': 'fm_param_count',
    'model_param_memory_mb': 'fm_model_param_memory_mb',
    'gpu_peak_memory_mb': 'fm_gpu_peak_memory_mb',
    'cpu_ram_delta_mb': 'fm_cpu_ram_delta_mb',
    'gflops_per_sample': 'fm_gflops_per_sample',
    'gflops_total': 'fm_gflops_total',
    'gflops_method': 'fm_gflops_method',
})
fm_df = fm_df.drop_duplicates(subset=['embedding_key'], keep='last')

mlp_join_df = mlp_df.rename(columns={
    'running_time_seconds': 'mlp_running_time_seconds',
    'param_count': 'mlp_param_count',
    'model_param_memory_mb': 'mlp_model_param_memory_mb',
    'gpu_peak_memory_mb': 'mlp_gpu_peak_memory_mb',
    'cpu_ram_delta_mb': 'mlp_cpu_ram_delta_mb',
    'gflops_per_sample': 'mlp_gflops_per_sample',
    'gflops_total': 'mlp_gflops_total',
}).copy()
mlp_join_df['embedding_key'] = mlp_join_df['embedding_file'].map(_normalize_path_str)

pipeline_df = mlp_join_df.merge(
    fm_df[['embedding_key', 'fm_running_time_seconds', 'fm_param_count', 'fm_model_param_memory_mb', 'fm_gpu_peak_memory_mb', 'fm_cpu_ram_delta_mb', 'fm_gflops_per_sample', 'fm_gflops_total', 'fm_gflops_method']],
    on='embedding_key',
    how='left',
)

matched = int(pipeline_df['fm_running_time_seconds'].notna().sum())
total_rows = int(len(pipeline_df))
print(f'[JOIN] FM matched rows: {matched}/{total_rows}')

pipeline_df['pipeline_running_time_seconds'] = pipeline_df['fm_running_time_seconds'] + pipeline_df['mlp_running_time_seconds']
pipeline_df['pipeline_gflops_total'] = pipeline_df['fm_gflops_total'] + pipeline_df['mlp_gflops_total']
pipeline_df['pipeline_gpu_peak_memory_mb'] = pipeline_df[['fm_gpu_peak_memory_mb', 'mlp_gpu_peak_memory_mb']].max(axis=1)
pipeline_df['pipeline_cpu_ram_delta_mb'] = pipeline_df['fm_cpu_ram_delta_mb'] + pipeline_df['mlp_cpu_ram_delta_mb']
pipeline_df['pipeline_param_count_total'] = pipeline_df['fm_param_count'] + pipeline_df['mlp_param_count']
pipeline_df['pipeline_model_param_memory_mb_total'] = pipeline_df['fm_model_param_memory_mb'] + pipeline_df['mlp_model_param_memory_mb']

ratio_order = {r: i for i, r in enumerate(RATIOS)}
pipeline_df['ratio_order'] = pipeline_df['ratio'].map(ratio_order).fillna(999).astype(int)
pipeline_df = pipeline_df.sort_values(['ratio_order', 'window_size', 'family', 'experiment', 'dataset']).reset_index(drop=True)

pipe_long_csv = TELEMETRY_DIR / f'pipeline_telemetry_long_{timestamp}.csv'
pipe_long_json = TELEMETRY_DIR / f'pipeline_telemetry_long_{timestamp}.json'
pipeline_df.drop(columns=['ratio_order', 'embedding_key']).to_csv(pipe_long_csv, index=False)
pipeline_df.drop(columns=['ratio_order', 'embedding_key']).to_json(pipe_long_json, orient='records', indent=2)

wide_metrics = [
    'balanced_accuracy', 'mcc', 'f1_weighted',
    'pipeline_running_time_seconds', 'pipeline_gflops_total',
    'pipeline_param_count_total', 'pipeline_model_param_memory_mb_total'
    ]
pipeline_wide = pipeline_df.pivot_table(
    index=['family', 'model_variant', 'window_size', 'dataset'],
    columns='ratio',
    values=wide_metrics,
    aggfunc='first',
)
pipeline_wide.columns = [f'{m}_{r}' for m, r in pipeline_wide.columns]
pipeline_wide = pipeline_wide.reset_index()

pipe_wide_csv = TELEMETRY_DIR / f'pipeline_telemetry_wide_{timestamp}.csv'
pipe_wide_json = TELEMETRY_DIR / f'pipeline_telemetry_wide_{timestamp}.json'
pipeline_wide.to_csv(pipe_wide_csv, index=False)
pipeline_wide.to_json(pipe_wide_json, orient='records', indent=2)

all_csv = SUMMARY_DIR / f'bestfold_inference_all_ratios_{timestamp}.csv'
all_json = SUMMARY_DIR / f'bestfold_inference_all_ratios_{timestamp}.json'
pipeline_df.drop(columns=['ratio_order', 'embedding_key']).to_csv(all_csv, index=False)
pipeline_df.drop(columns=['ratio_order', 'embedding_key']).to_json(all_json, orient='records', indent=2)

for ratio_name in RATIOS:
    df_ratio = pipeline_df[pipeline_df['ratio'] == ratio_name].drop(columns=['ratio_order', 'embedding_key'])
    if df_ratio.empty:
        continue
    ratio_csv = SUMMARY_DIR / f'bestfold_inference_ratio_{ratio_name}_{timestamp}.csv'
    ratio_json = SUMMARY_DIR / f'bestfold_inference_ratio_{ratio_name}_{timestamp}.json'
    df_ratio.to_csv(ratio_csv, index=False)
    df_ratio.to_json(ratio_json, orient='records', indent=2)
    print(f'[SAVED] {ratio_csv.name} | rows={len(df_ratio)}')
    print(f'[SAVED] {ratio_json.name} | rows={len(df_ratio)}')

legacy_json = SUMMARY_DIR / f'best_fold_inference_results_{timestamp}.json'
with open(legacy_json, 'w', encoding='utf-8') as f:
    json.dump(_to_serializable(legacy_inference_results), f, indent=2)

results_df = pipeline_df.copy()
print(f'\n[SAVED] {legacy_json.name} | experiments={len(legacy_inference_results)}')
print(f'[SAVED] {mlp_long_csv.name} | rows={len(mlp_df)}')
print(f'[SAVED] {pipe_long_csv.name} | rows={len(pipeline_df)}')
print(f'[SAVED] {pipe_wide_csv.name} | rows={len(pipeline_wide)}')
print(f'[SAVED] {all_csv.name} | rows={len(pipeline_df)}')
results_df.head(10)

Results root: d:\Splice_FMs_seq_lengths\results\classifiers
Embeddings root: d:\Splice_FMs_seq_lengths\data\embeddings
Telemetry root: d:\Splice_FMs_seq_lengths\results\pipeline_telemetry
Device: cuda
psutil available: True
Found experiments with results.json: 30
[SKIP-EXCLUDED] DNABERT-2-117M_CLS_w300_quick
[RUN] DNABert_zhihan1996/DNABERT-2-117M_w1000 | targets=10
[RUN] DNABert_zhihan1996/DNABERT-2-117M_w10000 | targets=10
[RUN] DNABert_zhihan1996/DNABERT-2-117M_w2000 | targets=10
[RUN] DNABert_zhihan1996/DNABERT-2-117M_w300 | targets=10
[RUN] DNABert_zhihan1996/DNABERT-2-117M_w600 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf_w1000 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf_w10000 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf_w2000 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf_w300 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-medium-160k-seqlen-hf_w600 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf_w1000 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf_w10000 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf_w2000 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf_w300 | targets=10
[RUN] HyenaDNA_LongSafari/hyenadna-small-32k-seqlen-hf_w600 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref_w1000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref_w2000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref_w300 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-500m-human-ref_w600 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species_w1000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species_w10000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species_w2000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species_w300 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-100m-multi-species_w600 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species_w1000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species_w10000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species_w2000 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species_w300 | targets=10
[RUN] NucleotideTransformer_InstaDeepAI/nucleotide-transformer-v2-250m-multi-species_w600 | targets=10
[JOIN] FM matched rows: 290/290
[SAVED] bestfold_inference_ratio_1_1_raw_20260412_170120.csv | rows=58
[SAVED] bestfold_inference_ratio_1_1_raw_20260412_170120.json | rows=58
[SAVED] bestfold_inference_ratio_1_1_10_20260412_170120.csv | rows=58
[SAVED] bestfold_inference_ratio_1_1_10_20260412_170120.json | rows=58
[SAVED] bestfold_inference_ratio_1_1_20_20260412_170120.csv | rows=58
[SAVED] bestfold_inference_ratio_1_1_20_20260412_170120.json | rows=58
[SAVED] bestfold_inference_ratio_1_1_50_20260412_170120.csv | rows=58
[SAVED] bestfold_inference_ratio_1_1_50_20260412_170120.json | rows=58
[SAVED] bestfold_inference_ratio_1_1_100_20260412_170120.csv | rows=58
[SAVED] bestfold_inference_ratio_1_1_100_20260412_170120.json | rows=58

[SAVED] best_fold_inference_results_20260412_170120.json | experiments=29
[SAVED] mlp_inference_telemetry_long_20260412_170120.csv | rows=290
[SAVED] pipeline_telemetry_long_20260412_170120.csv | rows=290
[SAVED] pipeline_telemetry_wide_20260412_170120.csv | rows=58
[SAVED] bestfold_inference_all_ratios_20260412_170120.csv | rows=290

,timestamp,stage,family,model_id,model_variant,experiment,window_size,dataset,ratio,best_fold_number,...,fm_gflops_per_sample,fm_gflops_total,fm_gflops_method,pipeline_running_time_seconds,pipeline_gflops_total,pipeline_gpu_peak_memory_mb,pipeline_cpu_ram_delta_mb,pipeline_param_count_total,pipeline_model_param_memory_mb_total,ratio_order
0,20260412_170120,mlp_inference,DNABert_zhihan1996,DNABERT-2-117M,DNABERT-2-117M,DNABERT-2-117M_w300,300,gencode,1_1_raw,5,...,18.129477,4.795247e+05,measured_profiler,18.903312,4.795525e+05,1529.661621,60.652344,117595907,448.592785,0
1,20260412_170120,mlp_inference,DNABert_zhihan1996,DNABERT-2-117M,DNABERT-2-117M,DNABERT-2-117M_w300,300,gtex,1_1_raw,5,...,18.129477,7.480585e+05,measured_profiler,29.277611,7.481018e+05,1530.482422,45.335938,117595907,448.592785,0
2,20260412_170120,mlp_inference,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf,hyenadna-medium-160k-seqlen-hf,hyenadna-medium-160k-seqlen-hf_w300,300,gencode,1_1_raw,5,...,3.899910,1.031526e+05,measured_profiler,22.787776,1.031665e+05,2560.872070,-41.539062,6815747,26.000011,0
3,20260412_170120,mlp_inference,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf,hyenadna-medium-160k-seqlen-hf,hyenadna-medium-160k-seqlen-hf_w300,300,gtex,1_1_raw,5,...,3.899910,1.609181e+05,measured_profiler,35.485477,1.609398e+05,2560.872070,17.125000,6815747,26.000011,0
4,20260412_170120,mlp_inference,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf,hyenadna-small-32k-seqlen-hf,hyenadna-small-32k-seqlen-hf_w300,300,gencode,1_1_raw,3,...,1.949955,5.157631e+04,measured_profiler,20.041319,5.159024e+04,1894.573242,440.363281,3542787,13.514660,0
5,20260412_170120,mlp_inference,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf,hyenadna-small-32k-seqlen-hf,hyenadna-small-32k-seqlen-hf_w300,300,gtex,1_1_raw,3,...,1.949955,8.045904e+04,measured_profiler,30.602077,8.048077e+04,1894.573242,46.152344,3542787,13.514660,0
6,20260412_170120,mlp_inference,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-500m-human-ref,nucleotide-transformer-500m-human-ref,nucleotide-transformer-500m-human-ref_w300,300,gencode,1_1_raw,3,...,48.477406,1.282227e+06,measured_profiler,26.249124,1.282269e+06,4156.910645,38.046875,481227748,1835.738174,0
7,20260412_170120,mlp_inference,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-500m-human-ref,nucleotide-transformer-500m-human-ref,nucleotide-transformer-500m-human-ref_w300,300,gtex,1_1_raw,3,...,48.477406,2.000275e+06,measured_profiler,41.289394,2.000340e+06,4156.910645,65.988281,481227748,1835.738174,0
8,20260412_170120,mlp_inference,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species,nucleotide-transformer-v2-100m-multi-species,nucleotide-transformer-v2-100m-multi-species_w300,300,gencode,1_1_raw,2,...,7.189709,1.901678e+05,measured_profiler,11.095122,1.901887e+05,3163.130859,68.789062,72115556,275.099014,0
9,20260412_170120,mlp_inference,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species,nucleotide-transformer-v2-100m-multi-species,nucleotide-transformer-v2-100m-multi-species_w300,300,gtex,1_1_raw,2,...,7.189709,2.966618e+05,measured_profiler,17.687529,2.966943e+05,3163.130859,23.976562,72115556,275.099014,0

In [2]:
# Tong hop nhanh theo ratio/dataset (FM + MLP + Pipeline)
display_cols = [
    'ratio', 'dataset', 'family', 'experiment', 'window_size',
    'balanced_accuracy', 'mcc', 'f1_weighted',
    'fm_param_count', 'fm_model_param_memory_mb', 'fm_gpu_peak_memory_mb', 'fm_cpu_ram_delta_mb', 'fm_gflops_per_sample', 'fm_gflops_total', 'fm_running_time_seconds',
    'mlp_param_count', 'mlp_model_param_memory_mb', 'mlp_gpu_peak_memory_mb', 'mlp_cpu_ram_delta_mb', 'mlp_gflops_per_sample', 'mlp_gflops_total', 'mlp_running_time_seconds',
    'pipeline_param_count_total', 'pipeline_model_param_memory_mb_total',
    'pipeline_gflops_total', 'pipeline_gpu_peak_memory_mb', 'pipeline_cpu_ram_delta_mb', 'pipeline_running_time_seconds',
    'n_samples', 'model_inference_seconds_total'
    ]

summary_df = results_df[display_cols].copy()
summary_df = summary_df.sort_values(['ratio', 'dataset', 'window_size', 'family', 'experiment']).reset_index(drop=True)

print('Summary rows:', len(summary_df))
summary_df.head(30)

Summary rows: 290

,ratio,dataset,family,experiment,window_size,balanced_accuracy,mcc,f1_weighted,fm_param_count,fm_model_param_memory_mb,...,mlp_gflops_total,mlp_running_time_seconds,pipeline_param_count_total,pipeline_model_param_memory_mb_total,pipeline_gflops_total,pipeline_gpu_peak_memory_mb,pipeline_cpu_ram_delta_mb,pipeline_running_time_seconds,n_samples,model_inference_seconds_total
0,1_1_10,gencode,DNABert_zhihan1996,DNABERT-2-117M_w300,300,0.327307,-0.009162,0.688535,117068544,446.581055,...,11.299094,0.006425,117595907,448.592785,1.949394e+05,1478.887695,-5.164062,7.763470,10752,0.075866
1,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf_w300,300,0.800521,0.456605,0.745772,6550528,24.988281,...,5.661949,0.003559,6815747,26.000011,4.193749e+04,2560.872070,16.250000,9.382492,10752,0.050889
2,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf_w300,300,0.778497,0.404754,0.681473,3277568,12.502930,...,5.661949,0.003581,3542787,13.514660,2.097158e+04,1894.573242,25.750000,7.992528,10752,0.056884
3,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-500m-human-ref_w300,300,0.904725,0.674920,0.879099,480438241,1832.726444,...,16.936239,0.006997,481227748,1835.738174,5.212460e+05,4156.910645,-25.433594,10.677385,10752,0.107271
4,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species_w300,300,0.417187,0.089684,0.434864,71719265,273.587284,...,8.480522,0.003855,72115556,275.099014,7.731223e+04,3163.130859,7.152344,4.435705,10752,0.057807
5,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-250m-multi-species_w300,300,0.452307,0.125394,0.683820,173855617,663.206547,...,11.299094,0.004788,174382980,665.218277,1.886052e+05,4242.734375,-12.500000,6.906270,10752,0.073835
6,1_1_10,gencode,DNABert_zhihan1996,DNABERT-2-117M_w600,600,0.331799,-0.001593,0.548820,117068544,446.581055,...,11.236041,0.004691,117595907,448.592785,3.824355e+05,1514.234863,5.937500,15.096788,10692,0.074748
7,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf_w600,600,0.550879,0.283022,0.757092,6550528,24.988281,...,5.630354,0.003622,6815747,26.000011,8.340127e+04,5820.423340,0.281250,18.240660,10692,0.050614
8,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf_w600,600,0.750767,0.379157,0.660647,3277568,12.502930,...,5.630354,0.003329,3542787,13.514660,4.170345e+04,5213.310059,-15.738281,15.791332,10692,0.054749
9,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-500m-human-ref_w600,600,0.909877,0.703072,0.893825,480438241,1832.726444,...,16.841728,0.006559,481227748,1835.738174,1.033121e+06,5091.003906,-1.082031,20.495339,10692,0.098238
10,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species_w600,600,0.429256,0.098497,0.667651,71719265,273.587284,...,8.433197,0.003924,72115556,275.099014,1.546922e+05,3825.481934,9.898438,9.017543,10692,0.062531
11,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-250m-multi-species_w600,600,0.429405,0.131440,0.743811,173855617,663.206547,...,11.236041,0.005747,174382980,665.218277,3.754062e+05,4234.764648,-22.000000,13.278459,10692,0.070521
12,1_1_10,gencode,DNABert_zhihan1996,DNABERT-2-117M_w1000,1000,0.345503,0.019971,0.733617,117068544,446.581055,...,11.122546,0.005600,117595907,448.592785,6.343325e+05,1385.870605,33.050781,25.733840,10584,0.165405
13,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf_w1000,1000,0.575775,0.241476,0.675868,6550528,24.988281,...,5.573481,0.003394,6815747,26.000011,1.375943e+05,5417.307617,-8.554688,35.651800,10584,0.052115
14,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf_w1000,1000,0.744747,0.346389,0.574075,3277568,12.502930,...,5.573481,0.003321,3542787,13.514660,6.879994e+04,4908.631836,17.527344,25.724887,10584,0.056277
15,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-500m-human-ref_w1000,1000,0.878874,0.625620,0.856702,480438241,1832.726444,...,16.671610,0.007223,481227748,1835.738174,1.747070e+06,4953.945801,-3.609375,36.124137,10584,0.103463
16,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species_w...,1000,0.363228,0.039807,0.285118,71719265,273.587284,...,8.348014,0.003961,72115556,275.099014,2.650022e+05,3802.817383,-22.281250,15.858039,10584,0.066514
17,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-250m-multi-species_w...,1000,0.389191,0.057712,0.567378,173855617,663.206547,...,11.122546,0.008337,174382980,665.218277,6.385416e+05,4152.925293,-5.437500,23.387515,10584,0.093069
18,1_1_10,gencode,DNABert_zhihan1996,DNABERT-2-117M_w2000,2000,0.329692,-0.000399,0.504938,117068544,446.581055,...,11.198209,0.004993,117595907,448.592785,1.316904e+06,1764.147461,2.109375,55.723185,10656,0.073501
19,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf_w2000,2000,0.648311,0.281056,0.630816,6550528,24.988281,...,5.611396,0.003609,6815747,26.000011,2.770550e+05,5420.559570,-8.613281,71.869743,10656,0.057963
20,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf_w2000,2000,0.787500,0.413070,0.681643,3277568,12.502930,...,5.611396,0.004902,3542787,13.514660,1.385303e+05,4912.227539,-8.191406,69.468127,10656,0.051631
21,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-500m-human-ref_w2000,2000,0.920345,0.724806,0.902686,480438241,1832.726444,...,16.785022,0.006677,481227748,1835.738174,3.529020e+06,4993.992676,2.796875,77.420856,10656,0.100516
22,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species_w...,2000,0.366892,0.081175,0.762262,71719265,273.587284,...,8.404803,0.003965,72115556,275.099014,5.510604e+05,3962.483398,-9.601562,35.911208,10656,0.058858
23,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-250m-multi-species_w...,2000,0.407545,0.068227,0.619924,173855617,663.206547,...,11.198209,0.005887,174382980,665.218277,1.306974e+06,4266.068359,-46.320312,50.660221,10656,0.070956
24,1_1_10,gencode,DNABert_zhihan1996,DNABERT-2-117M_w10000,10000,0.340203,0.003895,0.626378,117068544,446.581055,...,11.198209,0.005095,117595907,448.592785,1.316904e+06,665.825195,15.000000,87.185926,10656,0.074592
25,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-medium-160k-seqlen-hf_w10000,10000,0.758371,0.398414,0.708598,6550528,24.988281,...,5.611396,0.003428,6815747,26.000011,2.771935e+05,4675.127930,14.625000,378.856404,10656,0.051919
26,1_1_10,gencode,HyenaDNA_LongSafari,hyenadna-small-32k-seqlen-hf_w10000,10000,0.715991,0.378952,0.732192,3277568,12.502930,...,5.611396,0.003469,3542787,13.514660,1.385996e+05,4356.389648,13.851562,347.251733,10656,0.055308
27,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-100m-multi-species_w...,10000,0.377177,0.036677,0.523665,71719265,273.587284,...,8.404803,0.003884,72115556,275.099014,5.510604e+05,4609.492188,-56.718750,407.037724,10656,0.058471
28,1_1_10,gencode,NucleotideTransformer_InstaDeepAI,nucleotide-transformer-v2-250m-multi-species_w...,10000,0.354354,0.026643,0.591561,173855617,663.206547,...,11.198209,0.004692,174382980,665.218277,1.306974e+06,4905.786133,1.468750,530.950987,10656,0.073583
29,1_1_10,gtex,DNABert_zhihan1996,DNABERT-2-117M_w300,300,0.337794,0.012018,0.697286,117068544,446.581055,...,17.339569,0.008480,117595907,448.592785,2.991537e+05,1485.358887,16.425781,11.855570,16500,0.075866